### ISSUE TITLE
compile error on HP-UX

### ISSUE THREAD

**Issue by zhongk** [alanxz/rabbitmq-c#183]
When I run ./configure,the last error message is :
checking for library containing getaddrinfo... no
checking for socket in -lgetaddrinfo... no
configure: error: cannot find name resolution library (library with getaddrinfo symbol)

So I copy the older configure and libtool to pass it.
I met 2 compile error after make :

  CC       librabbitmq/librabbitmq_librabbitmq_la-amqp_connection.lo
"librabbitmq/amqp_socket.h", line 47: warning #2231-D: declaration is not
          visible outside of function
  typedef ssize_t (*amqp_socket_writev_fn)(void *, struct iovec *, int);
"librabbitmq/amqp_connection.c", line 447: error #2070: incomplete type is not
          allowed
      struct iovec iov[3];
                         ^

  CC       librabbitmq/librabbitmq_librabbitmq_la-amqp_timer.lo
"librabbitmq/amqp_timer.c", line 94: error #2020: identifier "CLOCK_MONOTONIC"
          is undefined
    if (-1 == clock_gettime(CLOCK_MONOTONIC, &tp)) {
                                        ^

**Comment by alanxz** [comment]
AFAIK this is fixed (or if it isn't I have no way to test to see if is actually fixed.  Closing.
