### ISSUE TITLE
CMake compile Windows 64 bit release/debug lib

### ISSUE THREAD

**Issue by pachuka** [alanxz/rabbitmq-c#233]
Hi,

I'm having some trouble figuring out if it's possible to build 64-bit libs on Windows and if so the commands to configure CMake to do so. I have the 32-bit version building fine, but would like to be able to use the lib with a 64-bit app.

Thanks,
Piyush

**Comment by alanxz** [comment]
When you run CMake for the first time you'll need to specify a generator with Win64 in the name, e.g., "Visual Studio 12 2013 Win64"

See: http://www.cmake.org/cmake/help/v3.0/manual/cmake-generators.7.html

**Comment by pachuka** [comment]
Awesome, thanks for the quick response! Still getting used to using CMake =)
