### ISSUE TITLE
Please add a link to the GitHub pages from the repo description

### ISSUE THREAD

**Issue by autarch** [alanxz/rabbitmq-c#234]
They're a bit difficult to find short of simply searching using a search engine. It'd be nice to set these as the site associated with the repo.

**Comment by alanxz** [comment]
You referring to: http://alanxz.github.io/rabbitmq-c/ ?

**Comment by autarch** [comment]
@alanxz - I was, but then I realized that doesn't link to the doxygen docs. Those were what I was really looking for.

**Comment by alanxz** [comment]
Gotcha. I should really delete that page as I don't keep it updated. 

The Doxygen docs should be linked from the README.md which should be displayed from http://github.com/alanxz/rabbitmq-c. Is the link to the API docs something that I should make more prominent?

**Comment by autarch** [comment]
I made a PR for this, #235

**Comment by alanxz** [comment]
Thanks for the quick patch. Merged.
