### ISSUE TITLE
compile error MacOS

### ISSUE THREAD

**Issue by brandonroth** [alanxz/rabbitmq-c#238]
When trying to build an Xcode project on Mac OS Yosemite with XCode6.1.1  I get the error "Cannot find name resolution library (containing symbol getaddrinfo)".  I'm using CMake 3.0.2 with the ios-cmake toolchain file.  The file on code.google.com needed a couple updates, one to find the correct Xcode SDK directory and the other to find the correct path for clang.  I'm not sure how to proceed, this seems like it's related to  #183

**Comment by alanxz** [comment]
When is this error happening? When you run CMake? Which file on code.google.com are you referring to?

It sounds like CMake is having trouble finding right library to link to to get the getaddrinfo() symbol.

This is almost certainly un-related to #183, which deals with an old version of autoconf on HP-UX.

**Comment by brandonroth** [comment]
The ios-cmake project i'm referring to is here https://code.google.com/p/ios-cmake/ and I'm running the command as described in their wiki which is where I get the failure.  If I skip the DCMAKE_TOOLCHAIN_FILE option and have it use the Xcode generator it works but that generates a Mac target which builds a dynamic library whereas I need a static library for iOS (for armv7, armv7s and arm64). I'm able to build the sample projects form the ios-cmake project.

**Comment by alanxz** [comment]
It appears that CMake can't figure out what library needs to be linked against in order to use getaddrinfo() on iOS.  You could try commenting out this block: https://github.com/alanxz/rabbitmq-c/blob/8a7c75899b4d489bad7405e918e6ea74d649d31a/CMakeLists.txt#L65-L100, to try and skip this detection code.
