### ISSUE TITLE
channel_max negotiation

### ISSUE THREAD

**Issue by carlhoerberg** [alanxz/rabbitmq-c#242]
Be able to negotiate (use the lowest, but not zero, of the suggested value from the server or the client) connection tune parameters.

**Comment by alanxz** [comment]
This is already implemented (see [amqp_socket.c](https://github.com/alanxz/rabbitmq-c/blob/bfd8cc9129da46136691a88c06d505b78f0043ae/librabbitmq/amqp_socket.c#L1278)).  It is exposed from the public API by specifying a positive value for channel_max in [amqp_login](https://github.com/alanxz/rabbitmq-c/blob/bfd8cc9129da46136691a88c06d505b78f0043ae/librabbitmq/amqp_socket.c#L1278) (and [friends](https://github.com/alanxz/rabbitmq-c/blob/9b404bfafc8e20cb718ce1802bb1d7dc21881642/librabbitmq/amqp.h#L1797)).  Note that amqp_connection_tune probably shouldn't be used (see comments in amqp.h for why).

**Comment by carlhoerberg** [comment]
Awesome, thank you! :) 

I read this comment and came under the impression that it wasn't implemented: https://github.com/alanxz/rabbitmq-c/blob/9b404bfafc8e20cb718ce1802bb1d7dc21881642/librabbitmq/amqp.h#L1054 
Glad to be proven wrong.
