### ISSUE TITLE
amqp_basic_qos and amqp_queue_purge using problem

### ISSUE THREAD

**Issue by znoodl** [alanxz/rabbitmq-c#246]
Hi!

When using amqp_basic_qos(), consumer can receive message but the server can not unack message. It make amqp_basic_ack() does not work.

I don't know amqp_queue_purge() can do, though maybe it can delete all message from a queue, but it can't(maybe just here).

**Comment by alanxz** [comment]
Its unclear to me what you're trying to do. What parameters are you calling amqp_basic_qos with? When you created the consumer, which parameters did you pass? Note that basic.qos is stateful on the channel: see: https://www.rabbitmq.com/consumer-prefetch.html

amqp_queue_purge() will delete all messages in the queue that have not been delivered and are awaiting an ack. (see: https://www.rabbitmq.com/amqp-0-9-1-reference.html#queue.purge).

**Comment by znoodl** [comment]
Thanks for your reply.
I am sorry for not clearly expressed what i'm trying to do, but your reply solved my problem.
I'll read the docs more.
Thank you!
