### ISSUE TITLE
amqp_basic_publish doesn't return an error when routingkey is wrong.

### ISSUE THREAD

**Issue by ppLorins** [alanxz/rabbitmq-c#247]
I invoke amqp_basic_publish with an existing exchange name and an invalid rouingkey ,
 also the  'mandatory' flag seted to true.I think this will lead the msg to go anywhere but to be 
dropped by the broker, and also the amqp_basic_publish should return an errCode to indicate 
this error. Here is the code:
![11](https://cloud.githubusercontent.com/assets/5534049/6521427/b3fcf2ae-c412-11e4-8d80-f36817204eda.png)

But in fact, amqp_basic_publish return 0 , that made me can't be sure whethere the message
 is routed  to a queue or not.

I guess I missunderstand something about the usage of rabbitmq-c.  Could anyone help ?

**Comment by emarcotte** [comment]
I believe you need to use publish confirmations to get this feedback.

**Comment by alanxz** [comment]
See: https://github.com/alanxz/rabbitmq-c/blob/244034c6aa95fd0c9f37df54766123db4baa9ec3/librabbitmq/amqp.h#L1834

(The return value you get from amqp_basic_publish does not indicate success or failure on the broker).

@emarcotte is correct: if you want to ensure your message makes it to a queue on the broker, you need to enable publisher confirms, and then wait for the basic.ack to be returned from the broker after publishing the message.
