### ISSUE TITLE
server->client communication fails after several hours

### ISSUE THREAD

**Issue by cbrake** [alanxz/rabbitmq-c#248]
Hi, I have a situation where I want to have a long running connection from a client to a server.  I can simulate this situation with:

amqp-consume --exclusive -u amqp://<my server> -q site_8888  cat

I use the rabbitmq management web interface to publish data to the queue.  Initially it works fine, but after several hours, and definitely after 1/2 day or so, when I publish data from the server, it is not received by the amqp-consume and is not acknowledged.  After perhaps another 1/2 day, the queue disappears on the server.  If I stop amqp-consume, the queue disappears immediately.  

I've tried 3 different servers:

F19: RabbitMQ 3.1.5, Erlang R16B02
F21: RabbitMQ 3.1.5, Erlang 17
Arch Linux (my workstation): RabbitMQ 3.3.1, Erlang 17

The Fedora machines are remote, and the Arch Linux system is local.  I can't reproduce the failure on my local rabbitmq server.  

Any ideas why this is happening?  Am I using rabbitmq incorrectly?  Is there any way to keep tabs on the health of the connection?

Thanks,
Cliff

**Comment by alanxz** [comment]
What's probably happening is some piece of network equipment is silently dropping one or both halves of the TCP connection.

The solution is to enable heartbeats on the connection. (which isn't enabled in the amqp-consume tool... yet).

Could you try fetching the tools_heartbeat branch (see: #249), build and run with the --heartbeat=60 flag.

**Comment by cbrake** [comment]
Thanks for the suggestion.  Started a test this morning and no issues after 10 hours or so.  I'm starting a parallel test without heartbeat as a control, and will check tomorrow.

**Comment by cbrake** [comment]
confirmed -- with heartbeat set to 600, still connected after 24 hours.  Test running without heartbeat, I lost the connection.
