### ISSUE TITLE
Question: different between envelop.message.body and envelop.message.pool

### ISSUE THREAD

**Issue by richzw** [alanxz/rabbitmq-c#253]
I have one producer based on `nodejs` and the javascript library which I used is [amqp.node](https://github.com/squaremo/amqp.node), and the consumer is implemented by [C library](https://github.com/alanxz/rabbitmq-c).

From rabbitmq management web, I can see the messages are pushed into the queue and delivered to the consumer. In the consumer, the `amqp_consume_message` return `AMQP-RESPONSE-NORMAL`, however, the `envelop.message.body` is null. 

After further investigation, I find those messages are stored in the `envelop.message.pool.pages`. I want to the different between `message.body` and `message.pool`?

**Comment by alanxz** [comment]
The `pool` field of the `amqp_message_t` object (e.g., `envelope.message.pool1) is a memory pool used for allocating parts of the message. It is an implementation detail and should not be used by client code directly (this implementation detail is subject to change).

The only reason that the `envelope.message.body.bytes` should be `NULL` with a `AMQP_RESPONSE_NORMAL` return value is if a 0-length message body is received.

**Comment by richzw** [comment]
Actually, the messages stored in the `envelop.message.pool.pages` is that buffer which sent from Node.js. **Why the `envelop.message.body.bytes` is `NULL`?**.

**Comment by alanxz** [comment]
You could run it under gdb and see what sets `envelope.message.body.bytes = NULL`.

In order for me to help you further, I will need a couple things: 
- Which version of rabbitmq-c are you running against?
- Which version of the RabbitMQ broker are you running against?
- What platform are you running your program on?
- A **short** snippet of code that demonstrates your issue.

**Comment by richzw** [comment]
- rabbitmq-c version v0.5.0
- RabbitMQ broker version 3.4.4
- running on windows 7 enterprise

Please find the codes in this [gist](https://gist.github.com/richzw/a80680e149ec492116bf)

**Comment by alanxz** [comment]
There have been several changes to that bit of code since v0.5.0. Please upgrade your rabbitmq-c to v0.6.0 and try and see if that fixes it.

**Comment by richzw** [comment]
I figure out the reason of this issue.

The reason is the byte alignment of my project is 1 byte. However, the byte alignment of `rabbitmq-c` is  default (4 bytes or 8 bytes)?, so

`reply = amqp_consume_message(m_con, &envelope, &m_time, 0)`

 the content of `envelope` returned from the above function is incorrect.

**Comment by alanxz** [comment]
How are you setting the alignment for your project?

**Comment by richzw** [comment]
All the `struct` date type defined in my project wrapped with `FIXED_LAYOUT` of `BOOST`. Also with 

`#pragma pack (1)` to make sure the byte alignment is 1 byte.

**Comment by alanxz** [comment]
I assume you have a good reason for doing this (there usually isn't a good reason to apply it to everything in a program).

Try surrounding any `#include` of a rabbitmq-c header with `#pragma pack(push)` and `#pragma pack(pop)`, which should reset it to the default structure alignment.

See: https://msdn.microsoft.com/en-us/library/2e70t5y1.aspx

Or better yet - only use `#pragma pack(1)` with structures you care about.

**Comment by alanxz** [comment]
Closing, this isn't a rabbitmq-c issue.
