### ISSUE TITLE
Check queue size before consuming

### ISSUE THREAD

**Issue by nvasta** [alanxz/rabbitmq-c#254]
For an existing queue, I am trying to create a passive queue with `amqp_queue_declare` and check the size of the stored messages using the returned `amqp_queue_declare_ok_t`. The weird thing is that it only works for the first time and is not updated, even if I recall the  `amqp_queue_declare` function. Could you provide an example of how to deal with that issue?

**Comment by alanxz** [comment]
RabbitMQ does not have the notion of a 'passive queue', I assume you mean that you're calling `amqp_queue_declare` with the passive bit set and understand the meaning of this flag as [described here](https://www.rabbitmq.com/amqp-0-9-1-reference.html#queue.declare).  Also note that you cannot get the size of the messages, only the number of messages in the queue from this call.

I don't understand what you mean by "it works the first time and is not updated". What isn't updated? How does it compare to what is presented on the broker management console?

**Comment by nvasta** [comment]
Yes you are right about the passive bit and I indeed want to monitor the number of messages in the queue (not size).

The first time the `amqp_queue_declare` is called this number coincides with the broker management console. Inside a while loop though, subsequent calls (after some more messages have been added in the queue) do not, and the number returned is zero.

**Comment by alanxz** [comment]
This feels like it might be a bug in the broker itself.  Try asking this on the [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users) discussion list.

**Comment by nvasta** [comment]
Ok I examined the issue a bit more and it seems that I probably had a misconception on the RabbitMQ operation. Once a queue has been bound to an exchange topic and a consumer is active, the queue length is always 0 (especially for non-ack queues) since the messages are probably directed straight to the consumer. This is true even if the consumer hasn't yet read them. Before consumption starts however, you can see the messages being accumulated in the queue. Weird but this is how I am seeing it!

**Comment by alanxz** [comment]
Glad you figured it out.
