### ISSUE TITLE
Support building as a static library on Win32

### ISSUE THREAD

**Issue by alanxz** [alanxz/rabbitmq-c#255]
The tests now need a static library to build, thus we need to figure out how to support building rabbitmq-c as a static library on Win32.

**Comment by rob100** [comment]
Could you explain why the static build was disabled in the first place? Perhaps I can help to fix the problem, a static lib on Windows would be great.

**Comment by alanxz** [comment]
Static builds on Win32 were disabled because of Win32's requirement of function declarations that call into shared libraries be decorated differently from function declarations that call into static libraries (IOW: use `__declspec(dllimport)` for DLLs and not for static libraries). The issue being its not possible to ship a header file that works with both shared and static libraries without requiring users to remember to define a preprocessor constant when compiling their code.

At the time I was concerned that this was going to cause an unnecessary amount of support headache having to explain this to various developers.

At this point I'm willing re-enable this, and mitigate potential issues by adding some documentation to this effect.

Technically all that needs to be done besides the documentation is remove the check from CMakeLists.txt and verify that it compiles and links correctly on Win32 (maybe add a row to the build matrix on AppVeyor). See [this](https://github.com/alanxz/rabbitmq-c/blob/112a54de4483c152fcc4ac65681f9f9bb7b55cbc/librabbitmq/amqp.h#L59) for how `amqp.h` currently handles it.
