### ISSUE TITLE
Heartbeat option not avaialble.

### ISSUE THREAD

**Issue by hitesh1818** [alanxz/rabbitmq-c#265]
Hello There,

  I am not able to set heartbeat option in the connection. is there any option to set heartbeat in your libarary. i found that java client & .Net client providing heartbeat option while connecting to server as connection option.

**Comment by alanxz** [comment]
There is partial support for heartbeats, see: https://github.com/alanxz/rabbitmq-c/blob/3546a7072cfc2a5b13194fe13378c4817d40dcb4/librabbitmq/amqp.h#L1739
