### ISSUE TITLE
Duplicate symbols when building for iOS

### ISSUE THREAD

**Issue by tagadapps** [alanxz/rabbitmq-c#269]
Gathering information from previous posts, I build rabbitmq-c this way
<code>cmake -DCMAKE_TOOLCHAIN_FILE=~/Documents/Development/Tools/iOS-cmake/ios-cmake/toolchain/iOS.cmake -DIOS_PLATFORM=SIMULATOR -DCMAKE_IOS_DEVELOPER_ROOT=/Applications/Xcode.app/Contents/Developer -DCMAKE_IOS_SDK_ROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.2.sdk -DENABLE_SSL_SUPPORT=False -DHAVE_HTONLL=True -GXcode ..</code>

When trying to use it in Xcode, I have the following error 
<small>
duplicate symbol ___sputc in:
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_api.o
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_connection.o
duplicate symbol ___sputc in:
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_api.o
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_framing.o
duplicate symbol ___sputc in:
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_api.o
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_mem.o
duplicate symbol ___sputc in:
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_api.o
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_socket.o
duplicate symbol ___sputc in:
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_api.o
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_table.o
duplicate symbol ___sputc in:
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_api.o
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_tcp_socket.o
duplicate symbol ___sputc in:
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_api.o
    /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c-0.6.0/build/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Objects-normal/i386/amqp_url.o
ld: 7 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</small>

I cant see where the duplicate symbols come from, any help would be appreciated.

**Comment by alanxz** [comment]
You shouldn't need to specify -DHTONLL=True to cmake, it should detect this automatically.

What version of CMake are you using?  What version of XCode are you using?  Have you defined any extra C flags? (using the CFLAGS environment variable, or in XCode itself)?

**Comment by tagadapps** [comment]
I am using Cmake 3.2.2, and XCode 6.2. I haven't defined any other C flags. I tried the DHTONLL flag because I had another error when trying to build in XCode without it. Here is the log:

<small>PhaseScriptExecution CMake\ PostBuild\ Rules build.ios/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Script-FED646AAF79B470CB024B8DA.sh
    cd /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c
    /bin/sh -c /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c/build.ios/librabbitmq/rabbitmq-c.build/Debug-iphonesimulator/rabbitmq.build/Script-FED646AAF79B470CB024B8DA.sh

echo "Creating symlinks"
Creating symlinks
/Applications/CMake.app/Contents/bin/cmake -E cmake_symlink_library /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c/build.ios/librabbitmq/Debug/librabbitmq.4.0.1.dylib /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c/build.ios/librabbitmq/Debug/librabbitmq.4.dylib /Users/Guillaume/Documents/Development/Libraries/iOS/rabbitmq-c/build.ios/librabbitmq/Debug/librabbitmq.dylib
CMake Error: cmake_symlink_library: System Error: No such file or directory
CMake Error: cmake_symlink_library: System Error: No such file or directory
make: *** [rabbitmq_buildpart_0] Error 1
</small>

Apparently, there is a name mismatch in the directory listed above: /librabbitmq/Debug does not exist, only /librabbitmq/Debug-iphonesimulator. Renaming to the expected name removes the symlinks error. I am able to compile and use the dynamic lib.

Is the directory supposed to be manually renamed ?
Thank you.

**Comment by alanxz** [comment]
I don't have any specific iOS-logic inside the CMakeLists.txt.  I suspect the issue i with the iOS.cmake toolchain file or CMake itself.

FYI: I don't think iOS supports dynamic libraries, make sure you provide -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON to CMake (it looks like you're already doing this).

Also for those who stumble upon this in the future here's how @tagadapps fixed it:
http://stackoverflow.com/questions/30242125/not-able-to-build-rabbitmq-c-for-ios-application

**Comment by tagadapps** [comment]
Thanks Alan, I actually realized right after I posted that the static lib is required, but it worked also, so everything is fine. Thanks for the support.
