### ISSUE TITLE
Binding Problem

### ISSUE THREAD

**Issue by Moheet51** [alanxz/rabbitmq-c#270]
Hello,
Using this library rabbitmq-c my code is succesfully running on simulator and binding with server, but when i am trying with any device, queue is generating but not getting bind.. 
I am stuck here.. please tell me what i am doing wrong.. 
Thank You.

**Comment by alanxz** [comment]
This is an issue tracker, not a support forum. Please post your question to [rabbitmq-users@](https://groups.google.com/forum/#!forum/rabbitmq-users) for help with the library.
