### ISSUE TITLE
amqp_queue_declare() hangs if the queue doesn't exist

### ISSUE THREAD

**Issue by leecbaker** [alanxz/rabbitmq-c#277]
I'm seeing the following behaviour:
If amqp_queue_declare() is called for a queue that doesn't exist, and passive = true, it hangs.

Instead of hanging, I expect it to return with an error code as described in the spec:
"If [the passive bit is] set, and the exchange does not already exist, the server MUST raise a channel exception with reply code 404 (not found)."
https://www.rabbitmq.com/amqp-0-9-1-reference.html#class.queue

Here's the backtrace I'm seeing:
```
    frame #0: 0x00007fff93e1333a libsystem_kernel.dylib`__recvfrom + 10
    frame #1: 0x000000010099e9ba librabbitmq.4.dylib`amqp_tcp_socket_recv + 90
    frame #2: 0x0000000100998db9 librabbitmq.4.dylib`amqp_socket_recv + 73
    frame #3: 0x0000000100999d27 librabbitmq.4.dylib`recv_with_timeout + 631
    frame #4: 0x000000010099a5a5 librabbitmq.4.dylib`wait_frame_inner + 1029
    frame #5: 0x000000010099a91e librabbitmq.4.dylib`amqp_simple_rpc + 206
    frame #6: 0x000000010099ac9d librabbitmq.4.dylib`amqp_simple_rpc_decoded + 109
    frame #7: 0x0000000100995c6b librabbitmq.4.dylib`amqp_queue_declare + 171
```
Using the 0.6.0 release from Macports on OS X Mavericks.

**Comment by alanxz** [comment]
Do you have a short example that demonstrates the problem?

Anything interesting in the RabbitMQ broker logs?

**Comment by leecbaker** [comment]
I upgraded to a newer version of rabbitMQ and the problem went away. Upgrade was from 3.1.5_2 (latest macports) to 3.5.3 (homebrew latest).

**Comment by alanxz** [comment]
Glad you figured it out.
