### ISSUE TITLE
Failed to declare exchange: table too large for buffer

### ISSUE THREAD

**Issue by pinipints** [alanxz/rabbitmq-c#278]
Downloaded the latest stable version. Built it on Mac using CMake. Thereafter did a 'make' command to generate the "librabbitmq.a" file.
When I try to create an exchange, it gives the following error:
Failed to declare exchange: table too large for buffer

**Comment by alanxz** [comment]
Minimal example that demonstrates the issue?

**Comment by alanxz** [comment]
I haven't heard anything in a while. Closing.
