### ISSUE TITLE
Build as 32-bit

### ISSUE THREAD

**Issue by hunter8** [alanxz/rabbitmq-c#281]
I'm trying to figure out how to build rabbitmq-c as a 32 bit shared or static library rather than 64 bit. I've spent a few hours messing with it but have made very little progress. Is there any feasible way to do this?

I'm running CentOS 6.6.

Thanks,
Hunter

**Comment by dhchen** [comment]
Built on ubuntu 10.04, 12.04 14.04 32 bit without any problem and running well for a long period of time.

**Comment by hunter8** [comment]
Great to know that it can be done, but how?

I'm more of a hardware guy (VLSI/HDLs); libraries and large complicated makefiles are fairly new to me. Adding -m32 just caused a ton of errors (as expected), and trying to trim out the SSL stuff which was giving me most of the errors didn't really get me anywhere.

**Comment by dhchen** [comment]
Just ./configure && make && make install
No makefile change required.

**Comment by alanxz** [comment]
@hunter8: make sure you've installed a 32-bit compiler and runtime:

On CentOS 6, I think you need this:

    yum -y install glibc-devel.i686 glibc-devel openssl-devel.i686

**Comment by hunter8** [comment]
@alanxz: I didn't have the openssl package installed, thank you.
@dhchen: Thank you for your help.

What I did (please let me know if this is wrong):
````
$ autoreconf -fi
$ ./configure --host=i686-linux-gnu "CFLAGS=-m32" "LDFLAGS=-m32"
$ make
$ sudo make install
````
That generated a 32 bit shared library and installed it. I still need to figure out why the flight software I'm trying to use it with refuses to load the library, but at least it's 32 bit now...

**Comment by alanxz** [comment]
Glad you were able to figure it out.
