### ISSUE TITLE
v0.7.0 on windows socket error

### ISSUE THREAD

**Issue by hjzljp** [alanxz/rabbitmq-c#282]
I test 0.7.0 on windows(7 and 8.1) with vs(2010 and 2013) build win32.
when i run examples like amqps_producer,amqps_consumer...
when they call amqp_login return error every time,both debug and release.
the console print: "Logging in: a socket error occurred"
I found in "amqp_tcp_socket.c,amqp_tcp_socket_recv,self->internal_error = amqp_os_socket_error();"
internal_error is 10054.

The server is ok , i test 0.7.0 on centos6 run success, and i also test 0.6.0 on windows success too.

**Comment by alanxz** [comment]
This might be a bug in rabbitmq-c. Try running the branch reference in #283 and see if it fixes this issue.

**Comment by hjzljp** [comment]
This branch work well,thank you.
