### ISSUE TITLE
amqp_login hang with connection port 15672

### ISSUE THREAD

**Issue by richzw** [alanxz/rabbitmq-c#284]
I know the port `15672` is used for management connection. However, I found `amqp_login` hang with connection port is 15672. Is there any issue with this incorrect configuration?

PS:
rabbitmq-c: v0.5.0
Running on visual studio 2013 under Windows

**Comment by alanxz** [comment]
What do you mean by issue?  

If you try to connect to a port serving HTTP/S with rabbitmq-c (an AMQP client), its not going to work. And by that I mean you should get a protocol or socket error from rabbitmq-c after a certain amount of time.

**Comment by richzw** [comment]
Actually, the main process will terminate itself if there is one thread hang after 30 seconds. 

Could you please tell me the actual time of socket error will return?

**Comment by alanxz** [comment]
The answer is that it depends on default timeouts set in the OS, and/or the behavior of the server that rabbitmq-c is attempting to speak AMQP with.

If its an HTTP server on the other end, the AMQP handshake doesn't send any `\n` as a part of its handshake, so the server probably will timeout waiting for a `\n` which will never come from rabbitmq-c.

**Comment by richzw** [comment]
Got it. Thank you for your information.
