### ISSUE TITLE
how to add property on header

### ISSUE THREAD

**Issue by ssalba** [alanxz/rabbitmq-c#288]
Can I add any key/value on header?

thanks!

**Comment by alanxz** [comment]
Yes.

You can populate the [`amqp_basic_properties_t.header`](https://github.com/alanxz/rabbitmq-c/blob/ff475742c6aa2911efece26f5caeab2ed736bfb7/librabbitmq/amqp_framing.h#L731) with a valid `amqp_table_t` object with arbitrary key/values (be sure to set the `AMQP_BASIC_HEADERS_FLAG` bit in the `_flags` field).
