### ISSUE TITLE
Compiling .7 or newer seg faults on build

### ISSUE THREAD

**Issue by jcarroll3** [alanxz/rabbitmq-c#290]
I've tried dumping all the source in a project, won't build. I've tried cmake w and w/o ios.cmake (the latter required modifiying some files to generate a proper Xcode project....so I may have messed something up there)

See Error below
====

1.	../Connection/AMQP/rabbitmq-c/amqp_private.h:333:1 <Spelling=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/usr/include/libkern/_OSByteOrder.h:75:28>: current parser token ')'
2.	../Connection/AMQP/rabbitmq-c/amqp_private.h:333:1 <Spelling=../Connection/AMQP/rabbitmq-c/amqp_private.h:299:3>: parsing function body '__builtin_constant_p'
3.	..Connection/AMQP/rabbitmq-c/amqp_private.h:333:1 <Spelling=../Connection/AMQP/rabbitmq-c/amqp_private.h:299:3>: in compound statement ('{}')
clang: error: unable to execute command: Segmentation fault: 11
clang: error: clang frontend command failed due to signal (use -v to see invocation)
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Thread model: posix
clang: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang: note: diagnostic msg:

**Comment by alanxz** [comment]
You've found a bug in Apple's version of clang. You should report this error to Apple using the provided link.

As for actually getting this compiled, I need to know more information:
- What version of XCode are you using?
- What version of CMake and which version of ios.cmake are you using?
- What other information would I need to re-create your environment?

**Comment by jcarroll3** [comment]
I did report to Apple but also wanted to report here to see if others ran into this. 

I'm having a hard time compiling for device and simulator. If I understand the code correctly (0.7) seems to have a bunch of update for 64-bit compatibility I'd like to have.

 Unless I'm using the commands wrong, using only CMake builds for MAC OS. And when I use iOS.cmake while I do get an xcode project, running into issues above. Which are same issues if I just drop the source in project. 

Details to your questions:
Xcode 6.4 (6E35b)
cmake version 3.3.0
ios.cmake (Grabbed from google code  "hg clone https://code.google.com/p/ios-cmake/" )

Tried many different commands, latest that got me the closest was

 cmake -DCMAKE_TOOLCHAIN_FILE=../../ios-cmake/toolchain/iOS.cmake -DENABLE_SSL_SUPPORT=False -GXcode ..

Had to remove an ifdef from CMakeLists.txt related to some Windows code I saw recommended from another post. Ill see if i can find that

**Comment by alanxz** [comment]
I've had a chance to try and reproduce this. I can't make the compile segfault (I also don't need to change around anything in rabbitmq-c to get a compile either).

Note that I did have to use a patched version of iOS.cmake as it doesn't handle CMake's try_compile() correctly. See: https://github.com/alanxz/ios-cmake/blob/master/toolchain/iOS.cmake
