### ISSUE TITLE
amqp_queue_declare stalls program

### ISSUE THREAD

**Issue by septag** [alanxz/rabbitmq-c#299]
Sometimes when amqp server doesn't respond (RabbitMQ) for queue declare, function _amqp_queue_declare_ stalls the program.
I'm also using _amqp_socket_open_noblock_ with a timeout when opening a new socket for connection.

**Comment by alanxz** [comment]
This is working as intended.

If the broker dies and doesn't close the network socket, then RPC functions like `amqp_queue_declare` will block until the OS decides that the TCP connection is dead and closes it, at which point `amqp_queue_declare` will return an error.
