### ISSUE TITLE
Support timeout in amqp_login*

### ISSUE THREAD

**Issue by alanxz** [alanxz/rabbitmq-c#300]
Add support for a timeout in the `amqp_login` and `amqp_login_with_properties` functions.

**Comment by kuroburki** [comment]
amqp_login failure returns in around 5 secs on my RHEL system. I also noticed the error message is same for two different cases: 1. Incorrect login credentials 2. Server unavailable. I verified this on the Web Client and it detected the failure reasons appropriately. Can this be addressed in the planned additions? It would help with proper error reporting.

**Comment by alanxz** [comment]
@kuroburki: which version of the RabbitMQ broker are you testing with?

**Comment by kuroburki** [comment]
I am currently on RabbitMQ Broker 3.6.5.

**Comment by alanxz** [comment]
Which version of rabbitmq-c are you using?  Support for the [auth-failure](http://www.rabbitmq.com/auth-notification.html) extension was added in the v0.7.0 release of rabbitmq-c.  amqp_login should fail with a connection.close method if the client fails to authenticate against the broker.

**Comment by alanxz** [comment]
This was added in #383
