### ISSUE TITLE
SSL peer cert verification failed

### ISSUE THREAD

**Issue by Daemon22** [alanxz/rabbitmq-c#303]
Hello,

I'm getting this error when i'm trying to connect using SSL certificate on this function:
amqp_socket_open(socket, hostname, port);

I'm only interested in server verification and not client verification, i set the cacert using this function:
amqp_ssl_socket_set_cacert(socket, "/path/to/cacert.crt");

I also tried to set the verify to false using:
amqp_ssl_socket_set_verify(socket, false);
but with the same error.

I change in the rabbitmq.config  from {verify, verify_peer} to {verify, verify_none}.
and set this {fail_if_no_peer_cert, false}.

Using the .NET C# api i'm able to connect to the same server when using:
rabbitMQFactory.Ssl.ServerName = "www.mysite.com";

any suggestion on how can i debug this issue?

**Comment by alanxz** [comment]
Currently its not possible to disable just one of the checks.  See: #180. 

I'd like to add this feature to rabbitmq-c in the near future. Stay tuned.
