### ISSUE TITLE
Broken/corrupted release package?

### ISSUE THREAD

**Issue by walrii** [alanxz/rabbitmq-c#315]
$ curl "https://github.com/alanxz/rabbitmq-c/releases/download/v0.7.1/rabbitmq-c-0.7.1.tar.gz" --create-dirs -L -o "rabbitmq-c-0.7.1.tar.gz"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  242k  100  242k    0     0   206k      0  0:00:01  0:00:01 --:--:--  500k
$ tar ztf rabbitmq-c-0.7.1.tar.gz
gzip: stdin is encrypted -- not supported
tar: Child returned status 1
tar: Error is not recoverable: exiting now

I've tried several methods of downloading but untaring results in the same error every time.

**Comment by alanxz** [comment]
I can also confirm that its not working. I'll try and upload a new version shortly.

**Comment by alanxz** [comment]
Uploaded working archive.
