### ISSUE TITLE
amqp_parse_url does not initialize amqp_connection_info

### ISSUE THREAD

**Issue by chjong** [alanxz/rabbitmq-c#319]
In amqp_parse_url(), parameter amqp_connection_info's ssl is not initialized.
Therefore, if the value is other than 0 (i.e., true), the offset calculation of user part will be incorrect. For example, user mike will be parsed as ike. 

The fix will be to put parsed->ssl = 1 in the beginning of amqp_parse_url().

**Comment by alanxz** [comment]
The semantics of `amqp_parse_url()` aren't well defined if the input contains garbage.

As a workaround for the moment make sure that the `amqp_connection_info` object that is passed is either zero-initialized (with `memset()`) or `amqp_default_connection_info()`.
