### ISSUE TITLE
amqp_ssl_socket_verify_hostname incorrect return value check

### ISSUE THREAD

**Issue by Daemon22** [alanxz/rabbitmq-c#330]
I have noticed that in file amqp_openssl.c line 272 there is a check of the return value:
```
if (verify_status){
    ...
}
```

After examination the function amqp_ssl_socket_verify_hostname return 1 on success and 0 on fail so the check should be
```
if (!verify_status){
    ...
}
```

**Comment by alanxz** [comment]
Argh, `int` really shouldn't be used as a way to indicate an error. That function has other issues: [`amqp_ssl_socket_verify_hostname`](https://github.com/alanxz/rabbitmq-c/blob/d8851bd7af1af4508269e766442ae638334e4266/librabbitmq/amqp_openssl.c#L168) returns 1 on success, 0 on failure, -1 on error.
