### ISSUE TITLE
Control message count in consume

### ISSUE THREAD

**Issue by mohammednaseef** [alanxz/rabbitmq-c#334]
Can there be a frame_max like configuration called message_count which restricts the number of messages consumed in amqp_consume_message(). The configuration can be set in amqp_connection_state structure.

**Comment by zbentley** [comment]
Isn't that what [`basic.qos`](https://www.rabbitmq.com/consumer-prefetch.html) is for?

**Comment by alanxz** [comment]
+1 to what @zbentley said: if you need to restrict the number of unacknowledged messages that the broker sends to the client use basic.qos on the channel you're consuming from.  If you want to stop consuming after a certain number of messages, use basic.qos to limit the number of unacknowledged messages, then basic.cancel once you've received the desired number of messages.

To be clear: I will not add this feature.
