### ISSUE TITLE
Setsockopt fails in amqp_basic_publish (cygwin on windows)

### ISSUE THREAD

**Issue by nickvane** [alanxz/rabbitmq-c#335]
Running example code amqp_sendstring results in socket error on amqp_basic_publish.
Other actions like, opening connection, opening channel, opening socket work.
The method fails on line 75 returning -1: 

    res = setsockopt(self->sockfd, IPPROTO_TCP, TCP_NOPUSH, &one, sizeof(one)); 

in method amqp_tcp_socket_send of amqp_tcp_socket.c

It has something to do with the AMQP_SF_MORE flag. If I replace AMQP_SF_MORE in the 2 lines in the method amqp_basic_publish:

    res = amqp_send_method_inner(state, channel, AMQP_BASIC_PUBLISH_METHOD, &m, AMQP_SF_MORE);

and

    res = amqp_send_frame_inner(state, &f, AMQP_SF_MORE);

with AMQP_SF_NONE, then there are no errors.
This is the first time I run this code on Windows. Our application (and rabbitmq-c) runs fine under openSuse 13.2.

**update**: Apparently, TCP_NOPUSH is a socket setting that is only available on freebsd platform. Somehow cygwin makes it available, but that setting cannot be set on windows. It probably returns an error when it tries to be set.

Kind regards, Nick

rabbitmq-c code: master branch at time of writing
System: windows 10 (latest update) with cygwin64 2.873 (2.3.1)
Build: cmake 3.3.2

**Comment by nickvane** [comment]
If I comment out:

    //#define TCP_NOPUSH      0x04    /* don't push last block of write */

in netinet/tcp.h then everything works. It looks like rabbitmq-c correctly checks the setting, but it is wrongly available in cygwin.

**Comment by alanxz** [comment]
I'm re-opening this as this is something that rabbitmq-c can work around.

**Comment by alanxz** [comment]
@nickvane rabbitmq-c should now work on unmodified cygwin. Let me know if you have any further issues.

**Comment by nickvane** [comment]
Awesome, thank you, it works!
