### ISSUE TITLE
Can you make public the functions from amqp_timer.cpp ?

### ISSUE THREAD

**Issue by Haster2004** [alanxz/rabbitmq-c#337]
Because in version 0.8.0 will appear a lot of noblock functions maybe it is a good idea to open
usefull amqp_timer functions?

**Comment by alanxz** [comment]
I'm hesitant to add functions to the public API without a good use case.

What would be the expected use case for these functions?

**Comment by Haster2004** [comment]
For example we have such use case:
1) open channel
2) delete queue
3) close channel

In my pull request I add nonblock types of such functions (because this methods are rpc methods and here we can get hang up if RabbitMQ server close connection abnormaly while we wait answer from it).

So all 3 calls are in one wrapper method like void deleteQueue(int timeout_ms)
And in body I don't want to get timeout = 3*timeout_ms, I want to compute it correct

**Comment by alanxz** [comment]
The internal timer API really was not designed to be exposed as a public interface. It would require a bit of thought and likely cleanup to make sure that its a solid interface.

Once #302 is complete, I will consider whether it makes sense to add this sort of functionality, vs allowing external users to develop timer interfaces that make sense to them.

**Comment by Haster2004** [comment]
As for me it misses function such
int amqp_time_ms_from_now(amqp_time_t *time, int ms_seconds);
that allow to create amqp_time_t from milliseconds )

**Comment by alanxz** [comment]
At this point I will not make the functions in amqp_timer.c publically accessible.
