### ISSUE TITLE
Compile with cmake

### ISSUE THREAD

**Issue by bilderkiste** [alanxz/rabbitmq-c#338]
Hi Alan,

Thank you very much for your rabbitmq-c binding!

You wrote that OpenSSL is optional. I tried to compile without, but with command cmake .. you will get the error, that suitable OpenSSL libraries are not installed. You should mention in your install guide, that libssl-dev is necessary to compile.

Christian

**Comment by alanxz** [comment]
OpenSSL can be disabled by passing -DENABLE_SSL_SUPPORT=OFF to cmake.

Leaving this open as a reminder to add that to the docs.

**Comment by alanxz** [comment]
Appears to already be in README.md.
