### ISSUE TITLE
amqp_basic_publish crashes

### ISSUE THREAD

**Issue by reset-today** [alanxz/rabbitmq-c#344]
Hi;
When using amqp_basic_publish (with protobufs), and the broker is restarted, my C++ client will crash. Here is the code. I tried surrounding it with a try/catch but no luck.
```result_publish = amqp_basic_publish(
                    zmq_context->conn,
                    2,
                    amqp_cstring_bytes(exchange.c_str()),
                    amqp_cstring_bytes(send_envelope.mutable_destination()->c_str()),
                    0,
                    0,
                    &zmq_context->props,
                    mq_response);
}```

Let me know if you need further information. Using /usr/lib/x86_64-linux-gnu/librabbitmq.so.4.1.4 on Linux Mint 17.1 and g++ 4.8.4

thanks

**Comment by alanxz** [comment]
You haven't given me a lot to go on here. You'll need to do some debugging before I can help you here.

What do you mean by crash? Is there a backtrace as to what caused the crash? Can you narrow your code down to a small snippet of code that demonstrates the issue? What version of rabbitmq-c are you using? (SONAME is good, version number is better - look in the amqp.h header for AMQP_VERSION_MAJOR and report the MAJOR, MINOR, and PATCH values).

rabbitmq-c is a C library, it doesn't throw exceptions, so try/catch won't help you here.

**Comment by reset-today** [comment]
alan:

the problem seems to be the same as explained in:
http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2013-October/030879.html
http://lists.rabbitmq.com/pipermail/rabbitmq-discuss/2013-November/032005.html

#define AMQP_VERSION_MAJOR 0
#define AMQP_VERSION_MINOR 8
#define AMQP_VERSION_PATCH 0

The program terminates with no errors on the cmd line (i; bad alloc, etc). And I can replicate it by restarting the downstream rabbitmq-server, whilst my client is running. It will always terminate during the amqp_basic_publish call. I don't have a backtrace, but I can get one for you.

**Comment by reset-today** [comment]
Alan:

Further to my last...
My C++ client uses certificates to communicate with the rabbitmq server. When the server is restarted, rabbitmq-c brings down my client. It always fails at the SSL_write call (line 91 in amqp_openssl.c). I don't why it brings the client down, but I think it may be an openssl bug. For testing purposes only...if I place a "SSL_renegotiate(self->ssl)" before this line, it won't fail. If I check the shutdown state via SSL_get_shutdown(self->ssl), I will only work (ie; notify me of a connection shutdown) only sometimes. Any ideas?

**Comment by reset-today** [comment]
sorry...hit the wrong button

**Comment by alanxz** [comment]
When the broker is restarted, all connections to it will be terminated. So its expected that something like SSL_write will return an error. At this point the amqp_connection_state_t will be in a closed state. The publisher code will need to destroy the amqp_connection_state_t object and create a new one (effectively reconnect to the broker and continue publishing).

SSL_renegotiate() is something that probably shouldn't be used, as there are bugs in the protocol that make this potentially not-secure.

I'd also suggest pulling down the latest master branch and running against that, there were some changes made recently that may have an affect on your use-case.

**Comment by reset-today** [comment]
just to clarify, I expect an error from SSL_write, but not a program termination, which is what is happening. SSL_renegiotiate() was used, as I said, for testing purposes only. I should have made it clear; there is no intention to use for fixing this issue. I recloned the master branch, built and installed it. Same problem.

**Comment by alanxz** [comment]
To clarify: you're seeing something inside of SSL_write causing your program to terminate?

**Comment by reset-today** [comment]
Yes. I place debugging messages before and after the ssl_write. It always fails on this call, when the server is restarted. And brings down the program with it.

**Comment by alanxz** [comment]
What version of OpenSSL is this happening with? Maybe try with a different version of OpenSSL?

**Comment by reset-today** [comment]
Yeh, I'll try the latest version and see how that goes

**Comment by alanxz** [comment]
Any luck?

**Comment by reset-today** [comment]
Caught up with other stuff. I'll let you know soon.

**Comment by reset-today** [comment]
When I tried to rebuild rabbitmq-c, I get this error

reset@bast ~/rabbitmq-c/build $ sudo cmake --build . --target install
[ 14%] Built target rabbitmq
[ 28%] Built target rabbitmq-static
Linking C executable amqp_bind
../librabbitmq/librabbitmq.so.4.1.4: undefined reference to `dlopen'
../librabbitmq/librabbitmq.so.4.1.4: undefined reference to `dlclose'
../librabbitmq/librabbitmq.so.4.1.4: undefined reference to `dlerror'
../librabbitmq/librabbitmq.so.4.1.4: undefined reference to `dlsym'
../librabbitmq/librabbitmq.so.4.1.4: undefined reference to `dladdr'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/amqp_bind] Error 1
make[1]: *** [examples/CMakeFiles/amqp_bind.dir/all] Error 2
make: *** [all] Error 2

locate libdl.so shows:

/lib/i386-linux-gnu/libdl.so.2
/lib/x86_64-linux-gnu/libdl.so.2
/lib32/libdl.so.2
/usr/lib/x86_64-linux-gnu/libdl.so

Any ideas?

**Comment by alanxz** [comment]
rabbitmq-c doesn't use `dlopen`, `dlerror`, or `dladdr`, I'm not sure why your build is picking those up, maybe use `nm` see if you can figure out what the library is pulling in that needs that.

**Comment by reset-today** [comment]
hey alan; don't know why that link error came up. reinstalled rabbitmq-c and rebuilt it and that error went away. Old openssl version =  OpenSSL 1.0.1f 6 Jan 2014. New one = OpenSSL 1.0.2g  1 Mar 2016. And the problem is still there. seems to be in last line of the "SSL_write" func in the openssl/ssl_lib.c file -> `return (s->method->ssl_write(s, buf, num));`

**Comment by alanxz** [comment]
A couple things that will help debug this further:

- We need to know what is actually causing the process to exit. Is it a SIGSEGV, maybe SIGPIPE (this actually makes sense in this case), something else?
- Can you get a backtrace at the point in which the process is exiting?
- If its a segfault, its helpful to know the value of various parameters when the process exits.

**Comment by reset-today** [comment]
It appears to be a SIGPIPE. I am getting some conflicting info here, and it *may* be another part of the program. Since we also use libuv (the event loop), it in conjunction with ssl, may be causing the issue. So, I'll spend a fair bit more time debugging this, and won't waste any more of your time. I'll close this issue, and if it is a rabbitmq-c/ssl issue, i'll raise a separate one. thanks alan.

**Comment by alanxz** [comment]
SIGPIPE makes sense. rabbitmq-c does not try to disable delivery of this signal when using SSL (whereas it does using the raw-TCP socket). OpenSSL unfortunately doesn't provide a good way to do this. It can be disabled on a per-process level by doing something like `signal(SIGPIPE, SIG_IGN);`.
