### ISSUE TITLE
Listening server with empty "exchange" parameter

### ISSUE THREAD

**Issue by nvkokorin** [alanxz/rabbitmq-c#353]
I trying to receive messages which associated with empty "exchange" parameter and unique bindingkey.
But when the "exchange" parameter is empty string (i.e. "") during start listening of the RabbitMQ server, error occurs:
Binding queue: server channel error 403h, message: ACCESS_REFUSED - operation not permitted on the default exchange.
For any other "exchange" values (except "amq.direct") I get the
Binding queue: server channel error 404h, message: NOT_FOUND - no exchange 'qwerty' in vhost '/'

Which reason for this? How I might use empty exchange? Thanks

**Comment by alanxz** [comment]
"" is the default exchange, its not possible to bind a queue to it explicitly. Implicitly all queues are bound to the default exchange with the routing key equal to the queue name, to publish to a queue, you can do a publish to the default exchange with using the queue as the routing key.

The NOT_FOUND error means that the exchange or queue you're trying to bind to doesn't exist. Make sure they're declared before trying to use them.  More information can be found in the tutorials, which explain AMQP concepts: http://www.rabbitmq.com/getstarted.html
