### ISSUE TITLE
Missing tar.gz file in v0.8.0 resources

### ISSUE THREAD

**Issue by davidjahn** [alanxz/rabbitmq-c#355]
We use the versioned `tar.gz` (eg. https://github.com/alanxz/rabbitmq-c/releases/download/v0.7.1/rabbitmq-c-0.7.1.tar.gz) file from the release. The file seems to be missing from the latest release `v0.8.0`. we would appreciate it if you can upload it. Thanks you!

**Comment by alanxz** [comment]
Is there any reason you cannot use the .zip file?

**Comment by RochesterinNYC** [comment]
@alanxz We can't use the .zip file because it does not come with `./configure` which we use in a build system that's based off autotools (https://github.com/alanxz/rabbitmq-c#autotools)

**Comment by RochesterinNYC** [comment]
Is the statement regarding legacy support for autotools made at that link no longer valid?

**Comment by bboozzoo** [comment]
@RochesterinNYC you can download `*.tar.gz` using Github, just follow this link: https://github.com/alanxz/rabbitmq-c/archive/v0.8.0.tar.gz (btw. works for any project, just put `/archive/<branch|tag|commit>` in URL right after project name).

As for `configure`, you can/should generate one by running `autoreconf [-if]` as part of the build process. There's no guarantee that the `configure` script that came inside the source tree will work on your system. For instance OpenEmbedded will automatically invoke `autoreconf` for autotools based packages if `configure` does not exist.

**Comment by alanxz** [comment]
@RochesterinNYC: you should be able to continue to use autotools to build rabbitmq-c, as @bboozzoo mentioned you'll want to run `autoreconf -i` to generate the `configure` script.

Eventually I would like to get rid of the autotools-based build system, as maintaining two independent build-systems is error-prone and is a source of unnecessary toil.  (That day has not arrived yet).

**Comment by RochesterinNYC** [comment]
All right, we've [followed your recommendations](https://github.com/cloudfoundry/binary-builder/commit/d00de3198b1adf693297513576ca3f0020c5ee85). Thanks. This can be closed now.
