### ISSUE TITLE
Fails to build with (upcoming) OpenSSL 1.1.0

### ISSUE THREAD

**Issue by fladi** [alanxz/rabbitmq-c#361]
During a recent rebuild of all Debian packages using OpenSSL with the upcoming 1.1.0 version, rabbitmq-c fails to build.

The rabbitmq-c build log is published at https://breakpoint.cc/openssl-1.1-rebuild-2016-05-29/Attempted/librabbitmq_0.7.1-1_amd64-20160529-1444

Some discussion about the OpenSSL API changes are at https://wiki.openssl.org/index.php/1.1_API_Changes

AFAICT the whole thread-handling seems to have been rewritten and would require a complete overhaul.

It's not yet fully decided if Debian will ship OpenSSL 1.1.0 in its next stable release or if it will stay with 1.0.2 for the time being.

**Comment by alanxz** [comment]
Thanks for the heads-up. 

Gotta love how the OpenSSL API changes page has zero mention of whats been changed in the locking APIs :/

**Comment by fladi** [comment]
It seems that OpenSSL upstream made some changes in their pre-releases. Right now, the build works again.

**Comment by alanxz** [comment]
Good news!
