### ISSUE TITLE
Detect rabbitmq-c disconnection

### ISSUE THREAD

**Issue by adolia** [alanxz/rabbitmq-c#363]
Hi!
How can I detect a rabbitmq-c disconnection of TCP socket and reconnect to server in two cases:
1. When network is down;
2. When socket is crushed.
?
Thanks in advance!

**Comment by alanxz** [comment]
This is a bug tracker and not a support forum.

If you still have questions, please ask on the [rabbitmq-c-users](https://groups.google.com/forum/#!forum/rabbitmq-c-users) or post it to [stackoverflow](http://www.stackoverflow.com) and use the [rabbitmq-c] tag.
