### ISSUE TITLE
The --server argument for tools is unusable

### ISSUE THREAD

**Issue by chad-iris** [alanxz/rabbitmq-c#364]
Any attempt to use the **--server** command line option with the amqp-* programs fails with the following message:

> both --server and --url options specify server host

even when **--url** has not been specified.

This is likely due to this bit of code in tools/common.c:
https://github.com/alanxz/rabbitmq-c/blob/master/tools/common.c#L242-L252

First, `amqp_default_connection_info(ci);` is called which sets most/all of the elements of the `ci` struct.

Then, `if (ci->host)` evaluates to true and triggers a `die()` with the message above, implying that  **--url** was used.  But `ci->host` has been set by the defaults, not by **--url**.

In effect, **--server** is unusable.  The same is probably true of **--port**, **--username**, **--password** and **--vhost**.

**Comment by chad-iris** [comment]
The obvious work-around is to specify the connection parameters using the **--url** option.

**Comment by alanxz** [comment]
Should be fixed in `master`.
