### ISSUE TITLE
amqp_pool_alloc get all heap

### ISSUE THREAD

**Issue by cfoursan** [alanxz/rabbitmq-c#365]
I run amqp_basic_comsume from one thread and bind in another. ( I've already read that it's not allowed :) ). In that case the application allocate all 8 Gb or RAM of my laptop. massif's output:

99.99% (2,592,424,517B) (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
->99.09% (2,569,145,344B) 0x8AE300: amqp_pool_alloc (in /home/vasilchenko/workspace/iqbus/build/test_iqbus)
| ->99.09% (2,569,142,272B) 0x8AF560: amqp_put_back_frame (in /home/vasilchenko/workspace/iqbus/build/test_iqbus)
| | ->99.09% (2,569,142,272B) 0x8B4012: amqp_consume_message (in /home/vasilchenko/workspace/iqbus/build/test_iqbus)

It's my fault of course. It's never happened if I work in one thread. But total freezing of my laptop isn't a good indication if that.

**Comment by alanxz** [comment]
Using a single `amqp_connection_state_t` object from multiple threads without synchronization will result in undefined behavior (meaning anything could happen, including consuming a large amount of RAM).  This is working as intended.

What are you expecting here?

**Comment by cfoursan** [comment]
Memory smashing and strange variable's values are the results of missed synchronization. I've never seen such behavior before.

**Comment by cfoursan** [comment]
I agree to close that ticker
