### ISSUE TITLE
question: librabbitmq async API?!

### ISSUE THREAD

**Issue by smititelu** [alanxz/rabbitmq-c#366]
Hi,

After googling a bit for this question, I've found some old comments (1-2 years) saying the at that point in time the library did not had any async API that "worked well".

My question is if some async API has been added in the meantime?

As a workaround, I can see I could use amqp_simple_wait_frame_noblock(..., with a timeout) in a newly spawned thread.

Regards,
Stefan

**Comment by alanxz** [comment]
Not yet. Follow along on #370 for updates on that.
