### ISSUE TITLE
0.8.0 release doesn't have `.tar.gz` with `./configure`

### ISSUE THREAD

**Issue by jemc** [alanxz/rabbitmq-c#374]
I maintain [a Ruby library that wraps this library](https://github.com/jemc/ruby-rabbitmq).

Part of the library installation script will download and build this C library from source.

The library currently uses version `0.6.0` of this library, but I want to upgrade to use `0.8.0`.  However, the GitHub releases for these are different.  Specifically, I noticed that some releases do not have the `tar.gz` that includes the `./configure` script.  Including the `./configure` script in the distribution is important, because it means my end-users don't need to have the dependencies required to build it from `configure.ac`.

The inclusion of this `tar.gz` in recent releases has been spotty, leading me to believe the omission in `0.8.0` is a mistake rather than a conscious decision to drop support.

* :white_check_mark:  `0.6.0` has `rabbitmq-c-0.6.0.tar.gz` 
* :x: `0.7.0` does not
* :white_check_mark: `0.7.1` has `rabbitmq-c-0.7.1.tar.gz` 
* :x: `0.8.0` does not

**Comment by alanxz** [comment]
See: #355.

**Comment by jemc** [comment]
I see.  Any chance of reconsidering?

In my case requiring the tools to build from `configure.ac` on the target deployment system is not feasible, which means to keep supporting these applications I'd need to fork this repo and mirror your releases, providing the `tar.gz` myself.

Perhaps if I do the work of generating the `tar.gz`, you could attach it to the github release?

**Comment by alanxz** [comment]
Could you tell me a bit about the deployment system you're targeting?

Eventually I would like to move away from autotools completely and have just 1 build system based off of CMake instead of trying to maintain 2.

**Comment by jemc** [comment]
> just 1 build system based off of CMake

That would present me with a different variation of the same problem, so I'm glad we're discussing that as well.

> Could you tell me a bit about the deployment system you're targeting?

Well, there are two broad categories of situation here:

1. Production RabbitMQ systems that I maintain in my current day job - it would be a pain to update all of the relevant `Dockerfile`s to temporarily install then uninstall `autotools` (or `cmake`), but it could be done.
2. Other users of my library working with systems that I don't maintain - the situations here are unknown and I don't have any control over them.  Moreover, these are users who often know nothing at all about C development - the C library is being built on their behalf without them having to worry about it.  It's reasonable for me to require `make` and `gcc` to be installed, as these are necessary for almost all C-using libraries, but to suddenly impose new build requirements on them is likely to lead to frustration and confusion, even if I include detailed warnings in the release notes - the vast majority of Ruby users can't really be expected to understand C-development concerns, and developers who maintain Ruby libraries that use C over FFI or C extensions try to shield them from these concerns as much as possible.

**Comment by alanxz** [comment]
How do Ruby users on Win32 handle this? AFAIK autotools doesn't work there (cross-platform is a major motivation for using CMake).

For 1), would that mean the image created by the `Dockerfile` includes GCC?  `cmake` or `autotools` feels like a similar dependency.

For 2) I understand the importance of a smooth install process, especially if end-users are not familiar with building stuff from source.  

It should be noted that the generated configure scripts do bake in assumptions about the system that they're built on. Mostly this shows when an older version of autotools is used, and a newer system has different directories it uses for libraries, so things get installed in the wrong place, but I've seen other odd errors.

Short-term, I'm willing generate a package with a configure script. Longer-term, it would be good to think about what makes the most sense from the deployment perspective.

**Comment by jemc** [comment]
> How do Ruby users on Win32 handle this?

Not sure.  I don't think I have any users on Windows, and I think Windows users are pretty underrepresented in the Ruby community in general - most develop on OSX or Linux.  Ruby itself has an installer for windows, but Ruby developers using windows often run into all sorts of problems - it's very much a "second class citizen" as an OS.  I personally don't have or use a Windows machine, so I don't have a way to confirm or provide support for it as a platform in any software I develop.

I can definitely understand your desire to support Windows for this C library, though, and I don't want to stand in the way of that if it's important to you and/or your users.

> For 1), would that mean the image created by the `Dockerfile` includes GCC? `cmake` or `autotools` feels like a similar dependency.

Right, GCC is temporarily installed in a similar way.  It is required for this library as well as some others that include C compilation in the build/install process.

> It should be noted that the generated configure scripts do bake in assumptions about the system that they're built on. Mostly this shows when an older version of autotools is used, and a newer system has different directories it uses for libraries, so things get installed in the wrong place, but I've seen other odd errors.

I personally haven't seen such issues with distributing a generated `configure` script, but I don't question your experience with maintaining a popular C library, so I definitely believe you that there can be problems.  If I found such problems to be common for users of my Ruby library, I'd have to consider alternative install process solutions, so I can understand the push for CMake.  Like you, I'm just trying to make a smooth install process.  I appreciate your willingness to have a dialogue about it.

**Comment by alanxz** [comment]
Uploaded the dist-package to the release.

Apologies for taking so long to get to this.
