### ISSUE TITLE
Consumer crashes when using a non zero heartbeat when opening a connection

### ISSUE THREAD

**Issue by cristeab** [alanxz/rabbitmq-c#375]
Hi

This is the code used by the consumer to open a connection:

```
int heartbeat = 60;// [seconds] timeout used to check if connection is alive when waiting for messages

    conn = amqp_new_connection();

    socket = amqp_ssl_socket_new(conn);
    if (!socket) {
        PRINT_ERR("creating SSL/TLS socket");
        exit(EXIT_FAILURE);
    }

    amqp_ssl_socket_set_verify_peer(socket, 0);
    amqp_ssl_socket_set_verify_hostname(socket, 0);

    status = amqp_socket_open(socket, hostname, port);
    if (status) {
        PRINT_ERR("opening SSL/TLS connection");
        exit(EXIT_FAILURE);
    }

    die_on_amqp_error(amqp_login(conn, VHOST, 0, 131072, heartbeat, AMQP_SASL_METHOD_PLAIN,
                                 username, password), "Logging in");
    amqp_channel_open(conn, CHANNEL);
    die_on_amqp_error(amqp_get_rpc_reply(conn), "Opening channel");
```

Now in order to wait for messaged from the broker:

```
amqp_frame_t frame;

    amqp_rpc_reply_t ret;
    amqp_envelope_t envelope;

    amqp_maybe_release_buffers(conn);
    ret = amqp_consume_message(conn, &envelope, NULL, 0);

    if (AMQP_RESPONSE_NORMAL != ret.reply_type) {
```

However, after the second message I always get a crash. When the heartbeat is set to 0 there is no crash but amqp_consume_message() blocks forever after long periods of inactivity. Do I miss something when enabling heartbeat or this should be considered a bug ?

**Comment by alanxz** [comment]
What do you mean by crash? Does the program segfault?  

I don't see anything obviously wrong with the code, but you've only pasted part of your code above.  Could you pare your code down to a complete example that demonstrates the issue?

FYI: this sort of question is better handled on the [rabbitmq-c-users](https://groups.google.com/forum/#!forum/rabbitmq-c-users) list or on stackoverflow using the rabbitmq-c tag.
