### ISSUE TITLE
How can batching controlled?

### ISSUE THREAD

**Issue by seongyun-ko** [alanxz/rabbitmq-c#376]
When producers(or consumers) publish(or consume) the messages, they can batch it to increase the throughputs.

How can I specify the maximum batch size / buffer size of batch queue ,... etc so that I can control the clients behaviors?

**Comment by zbentley** [comment]
For consumers, look into QoS: http://www.rabbitmq.com/consumer-prefetch.html. It's supported by this driver via the basic_qos methods. Also, for consumers with acknowledgements, you can `ack` multiple messages at once.

For publishers: you can't batch publishes _per se_ (I think?), but if you're using confirmations, you can publish multiple messages and await confirmation of all of their publishes at once, which saves a fair amount of time. This isn't automatically supported, but you can track message counts and IDs as you publish and await confirms for those tracked messages later on; see the examples for more info (and remember to turn on confirmations for your channel first). If publisher performance in terms of time-to-consumer is your chief concern, also look into relaxing durability guarantees on your queue and messages: https://www.rabbitmq.com/reliability.html

**Comment by seongyun-ko** [comment]
@zbentley thank you for your informative guide.

**Comment by alanxz** [comment]
@seongyun-ko looks like @zbentley answered your question, feel free to re-open to ask on the [rabbitmq-c-users](https://groups.google.com/forum/#!forum/rabbitmq-c-users) email list if you have any further questions.
