### ISSUE TITLE
The exact meaning of 'timeout' in amqp_consume_message

### ISSUE THREAD

**Issue by seongyun-ko** [alanxz/rabbitmq-c#378]
**timeout**: a timeout to wait for a message delivery. Passing in * NULL will result in blocking behavior.

Say that 'timeout' is set to X.

Does it mean that the consume function will wait for the new message delivery request only for X seconds (Until it starts)?
Or
Does it mean that the consume function will cancel the current delivery request and return if the request service time exceeds X seconds?

I guess, the former one would be the case. But just to make it sure.

**Comment by alanxz** [comment]
The former is correct (will wait for a message delivery to start for only X seconds).

FYI: these sorts of questions are better off answered on the [rabbitmq-c-users](https://groups.google.com/forum/#!forum/rabbitmq-c-users) mailing list.
