### ISSUE TITLE
SSL authentication

### ISSUE THREAD

**Issue by dimm0** [alanxz/rabbitmq-c#379]
I'm building the 0.8.0 version of the library in CentOS 6 and not getting ```amqp_ssl_socket_open``` function exported:
```
$nm -D /opt/librabbitmq/lib64/librabbitmq.so.4
...
000000000000b480 T amqp_simple_wait_frame_noblock
000000000000b500 T amqp_simple_wait_method
000000000000a1f0 T amqp_socket_get_sockfd
000000000000a1a0 T amqp_socket_open
000000000000a1b0 T amqp_socket_open_noblock
000000000000f610 T amqp_ssl_socket_new
000000000000f500 T amqp_ssl_socket_set_cacert
000000000000f490 T amqp_ssl_socket_set_key
000000000000f3a0 T amqp_ssl_socket_set_key_buffer
000000000000ee00 T amqp_ssl_socket_set_ssl_versions
000000000000edb0 T amqp_ssl_socket_set_verify
000000000000ed50 T amqp_ssl_socket_set_verify_hostname
000000000000ed80 T amqp_ssl_socket_set_verify_peer
000000000000c570 T amqp_table_clone
...
```

```stats_buffer.c:(.text+0x2a2): undefined reference to `amqp_ssl_socket_open'```

Is that expected? So far I can't connect to SSL, seems like it's trying to open a regular connection...

If that's expected, is there any example of using certs for authentication?

**Comment by alanxz** [comment]
`amqp_ssl_socket_open` is not a public API (and thus not exported).

Check out any of the amqps_*.c files in the examples directory to see how to connect using SSL. E.g., [amqps_connect_timeout.c](https://github.com/alanxz/rabbitmq-c/blob/master/examples/amqps_connect_timeout.c).
