### ISSUE TITLE
HI Alan, May I know how to get props field in when I consume rabbitMQ message in C. 

### ISSUE THREAD

**Issue by eshwar472** [alanxz/rabbitmq-c#384]
If you have example code for it, can you please point it out. I wanted to implement RPC-RabbitMQ in C language

**Comment by alanxz** [comment]
This is an issue tracker, not a support forum.

Please ask your question on [rabbitmq-c-users](https://groups.google.com/forum/#!forum/rabbitmq-c-users).

**Comment by eshwar472** [comment]
My mistake. I am sorry. I have posted there as well. Can u pls help me with
the answer in  rabbitmq-c-users
<https://groups.google.com/forum/#!forum/rabbitmq-c-users>.
