### ISSUE TITLE
when errno == `EINTR`, the library should return to caller as an error!

### ISSUE THREAD

**Issue by sangechen** [alanxz/rabbitmq-c#385]
rabbitmq-c: v0.8.0
OS: CentOS-6.6 / kernel-2.6.32-642.el6.x86_64 / using linuxbrew
compiler: gcc-5.3.0

amqp_tcp_socket.c  in function: amqp_tcp_socket_recv()
line: 146

```
      case EINTR:
        goto start;
```

amqp_socket.c:  in function: amqp_poll()
line: 297

```
      case EINTR:
        goto start_poll;
```

line: 348

```
      case EINTR:
        goto start_select;
```

I think these code should be deleted, and let the caller to process `EINTR` error (may schedule a retry). 

my situation:
I wrote a single-thread `consumer` program.
when it starts, it waits on a amqp-channel for msg.
and I install a SIGTERM to set a signal-handler for this program,
the signal-handler marks a exit_flag as `true`,
so when the next loop iteration checks this flag, the consumer will stop gracefully!

```
bool exit_flag = false;

static void consumer_sigterm_func(int sig)
{
    exit_flag = true;
}

int main(int argc, char **argv)
{
    //init `act` to function: consumer_sigterm_func
    sigaction(SIGTERM, &act, &oldact);

    while (exit_flag == false)
    {
        //wait on channel for msg, and process it.
    }
}
```

BUT this program can never be stoped normally!

when I use `kill -SIGTERM <pid>` try to stop the process, it has no effect!
the reason is the code I listed above: the EINTR error has been processed by the rabbitmq-c library.

I work around this problem by setting a timeout on the `wait` action.
so the control flow should break out periodically to check the `exit_flag`.

I think this is not an appropriate solution, so I submit an issue.

**Comment by sangechen** [comment]
some reference:
http://250bpm.com/blog:12
https://www.gnu.org/software/libc/manual/html_node/Interrupted-Primitives.html

**Comment by alanxz** [comment]
Unfortunately this is not something that is straight-forward to fix:

First, rabbitmq-c doesn't have any sort of support for maintaining state of a call if a socket returns `EINTR` and then returns all the way back to user code.  This matters if client-code wants to ignore `EINTR` and keep going (note that `EINTR` result from other signals such as `SIGPIPE`).   This is especially bad with the way the rpc-style calls currently work: its possible to be `EINTR` after a partial `send()` or a partial `recv()`.  Fixing this is doable, but a good deal more work that what you've suggested above.

Second, this would result in an API behavior change: any existing users of the library would need to change their code to correctly handle `EINTR` (or the rabbitmq-c equivalent of it ends up being).  This will cause a subtle bugs for existing users of the library that would not likely be caught by most unit of integration tests.

So while I can appreciate this as an issue, this isn't something that is going to change with `rabbitmq-c`. 

If your use-case is as simple as what you describe in your example above, I'd suggest using the default `SIGTERM` handler and letting the process terminate, or do whatever cleanup you can and call `exit()` at the end of the signal handler.

**Comment by sangechen** [comment]
Thx for your answer ^_^

but I still made a patch for self-use only, hope you don't mind.

**Comment by zbentley** [comment]
@sangechen can you please post a link to your patch, or the branch in your fork in which it has been made? This may be useful for others.
