### ISSUE TITLE
Missing API documentation

### ISSUE THREAD

**Issue by GeoffDanielson** [alanxz/rabbitmq-c#386]
"See examples" is not sufficient documentation of the API, especially when the examples are uncommented, save for the license.

Is there a good reference that is buried somewhere?

**Comment by alanxz** [comment]
There is some Doxygen generated docs here: http://alanxz.github.io/rabbitmq-c/docs/0.8.0/, which is derived from comments in the public headers (see `amqp.h`).

It's also useful to [understand how RabbitMQ works](http://www.rabbitmq.com/getstarted.html).
