### ISSUE TITLE
amqp-publish failing without error

### ISSUE THREAD

**Issue by firewave** [alanxz/rabbitmq-c#388]
I am trying to publish a message using amqp-publish, but all I am getting is 

opening socket to xxx.xxx.xxx.xxx:5672

The process exits with 1. An error message why it fails would be very helpful. I am able to connect and publish to the queue using various clients using the official RabbitMQ Java library and the management UI.

I tried the version bundled with Ubuntu 16.10 which is 0.8.0-1 and also built the latest master myself on Ubuntu 14.04, but they show the same. I am using an amqps:// URI and sending via an exchanged. I am able to telnet to the server on that port, so it doesn't appear to be a firewall issues.

Also sorry about making this an issue immediately, but the google group rabbit-c-users linked on the main page doesn't exist.

**Comment by alanxz** [comment]
Looks like a bad link in README.md.  I've corrected it in #389.

The real link is: https://groups.google.com/forum/#!forum/rabbitmq-c-users

The error you're getting is that it cannot connect to that host on that port.  Make sure that that host is listening on that port and that you can get to it from the host you're running your client on.  FYI: most RabbitMQ brokers use port 5671 for SSL connections.

**Comment by firewave** [comment]
As I wrote before it works with telnet. And although the broker just serves SSL connections it runs on port 5672.

The command I am using is

amqp-publish -u amqps://user:pass@xx.xxx.xxx.xx:5672/amqpVhost -e amqpExchange -b test -H "test: dummy"

**Comment by firewave** [comment]
I just tried  amqp-delete-queue and a totally different server and have the same issue. That server also supports non-SSL connections and those work. So it seems SSL connections are not working at all with the tools.

**Comment by alanxz** [comment]
Likely the SSL handshake is failing (yes the error message is lousy here). You may need to specify the `-cacert`, `-key`, and `-cert` flags when running it.

**Comment by firewave** [comment]
I couldn't get that to work either - same error. I assume I only need the --cert since all of them toget her make no sense to me.
I am having a different server now which also does non-SSL and it doesn't work either. I am getting

basic.publish: a socket error occurred

It can login and all, but the publish fails. I played a bit with the options and when I specify an non-existent exchange I get the same error message.

The server log says this:

=WARNING REPORT==== 22-Nov-2016::10:31:45 ===
closing AMQP connection <0.608.0> (xx.xxx.xxx.xx:33653 -> xx.xxx.xxx.xx:5671):
connection_closed_abruptly

**Comment by alanxz** [comment]
There was a bug in v0.8.0 version of the tools that was fixed a while back (#364). Could you try building from master and seeing if this issue still exists?

**Comment by firewave** [comment]
I am already using master - 99755d541657470b60985836f6535664bd8d8cbb to be precise.
