### ISSUE TITLE
Clean shutdown on SIGINT

### ISSUE THREAD

**Issue by MikePlayle** [alanxz/rabbitmq-c#390]
I have a program which needs to consume messages from RabbitMQ and shut down cleanly if it receives a SIGINT signal.

This is made awkward by this code in `amqp_tcp_socket_recv()`:

```c
start:
#ifdef _WIN32
  ret = recv(self->sockfd, buf, (int)len, flags);
#else
  ret = recv(self->sockfd, buf, len, flags);
#endif

  if (0 > ret) {
    self->internal_error = amqp_os_socket_error();
    switch (self->internal_error) {
      case EINTR:
        goto start;
```

This means that when my process receives a SIGINT, it executes the signal handler and then immediately restarts the `recv()` call.

It would be easier to handle signals cleanly and correctly if the EINTR error was passed up the call stack to the client code, rather than being swallowed like this.

**Comment by MikePlayle** [comment]
I got this slightly wrong: the problem seems to be occurring in `amqp_poll()` instead.

**Comment by MikePlayle** [comment]
On further thought, perha[ps what I need to do is use `amqp_get_sockfd()` and call `poll()` myself.

Is there a way to tell librabbitmq to read whatever it can from the socket and return, even if there isn't an entire message in the socket buffer yet?

**Comment by alanxz** [comment]
See #385 for a discussion on why rabbitmq-c handles EINTR and why this is hard to change.

**Comment by alanxz** [comment]
You're welcome to use `amqp_get_sockfd()` do heed the warning that rabbitmq-c may not provide API stability between releases: in other words rabbitmq-c may use the sockets differently release-to-release.

Calling [`amqp_simple_wait_frame_noblock`](https://github.com/alanxz/rabbitmq-c/blob/99755d541657470b60985836f6535664bd8d8cbb/librabbitmq/amqp.h#L1553) with a 0 timeout will have this effect. Note that the library buffers amqp_frame_t and unprocessed bytes if they were not consumed by the last operation, so you'll need to test for buffered bytes with [`amqp_data_in_buffer`](https://github.com/alanxz/rabbitmq-c/blob/99755d541657470b60985836f6535664bd8d8cbb/librabbitmq/amqp.h#L2054) and enqueued frames with [`amqp_frames_enqueued`](https://github.com/alanxz/rabbitmq-c/blob/99755d541657470b60985836f6535664bd8d8cbb/librabbitmq/amqp.h#L1432)

**Comment by MikePlayle** [comment]
Thanks. I can understand that this is hard to change.

On further thought, I'm not sure that the approach of setting a flag in the signal handler could be made to work reliably, even if EINTR errors were to be propagated upwards like this. After all, a signal can be received at any time - even immediately before entering the poll() syscall! So in this approach it would still be possible for the library to block indefinitely with the exit flag set.

For now I've taken a very hacky approach, which is to retrieve the file descriptor with amqp_get_sockfd() and then close() it from inside the signal handler. This has the desired effect of causing librabbitmq to unwind its stack immediately, but I'm not very comfortable with it. One major problem is that this approach will only work for shutdown; if I want to trigger other actions with signals (such as reloading a config file in response to SIGHUP) then this method won't work.

A method I've used before in other cases is to create a pipe, pass the reading end to poll(), and have the signal handler write something to the writing end. This gives a reliable and race-free way of waking up the poll() call. Do you think something like this could be integrated into librabbitmq and triggered by an exported `amqp_interrupt()` function or some such? Client signal handlers could then call into this function to trigger an immediate return.

**Comment by alanxz** [comment]
`amqp_interrupt()` is an interesting idea. My initial thoughts on this are:

1. Implementing this portably would be tricky. Win32/Winsock doesn't offer a way to do this using the posix-like `select()` against a pipe. The concept of signals doesn't exist on Win32, there's likely a way to do this using event-handles, though we're starting to introduce a bunch of non-portable code once we head down this path.
1. Would still need to deal with the "what state is the connection in if it gets interrupted" problem. The easiest thing to do would be to put the connection into an 'invalid-but-connected' state, where the only allowable action would be to close the underlying socket. A more complex change would be to remember the call that the code made, and require that code to restart the call if they wished to continue or close the socket; any other call would be invalid.  This is likely to be tricky to get right.
1. We'd need to consider carefully the situation where the blocking call is occurring in a different thread than where the signal handler is being run.

So my immediate answer is not 'no', but like returning `EINTR` its certainly not a straight-forward things to add.
