### ISSUE TITLE
Can't build the rabbitmq-c Ver 0.8.0 - an error in "depend.make"

### ISSUE THREAD

**Issue by alekseYY** [alanxz/rabbitmq-c#393]
I'm trying to build the 0.8.0 version - please see an error below. May be, it's something on my side, but where to look? Actually, I don't need examples for now - how to build without them?

OS: Linux ubuntu 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

user@ubuntu:~/rabbitmq-c-0.8.0/build$ cmake --build .
Scanning dependencies of target rabbitmq
[  1%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_framing.c.o
[  2%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_api.c.o
[  3%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_connection.c.o
[  4%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_mem.c.o
[  5%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_socket.c.o
[  6%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_table.c.o
[  6%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_url.c.o
[  7%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_tcp_socket.c.o
[  8%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_time.c.o
[  9%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_consumer.c.o
[ 10%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_openssl.c.o
[ 11%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_openssl_hostname_validation.c.o
[ 12%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_hostcheck.c.o
[ 12%] Linking C shared library librabbitmq.so
[ 12%] Built target rabbitmq
Scanning dependencies of target rabbitmq-static
[ 13%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_framing.c.o
[ 14%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_api.c.o
[ 15%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_connection.c.o
[ 16%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_mem.c.o
[ 17%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_socket.c.o
[ 18%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_table.c.o
[ 18%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_url.c.o
[ 19%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_tcp_socket.c.o
[ 20%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_time.c.o
[ 21%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_consumer.c.o
[ 22%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_openssl.c.o
[ 23%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_openssl_hostname_validation.c.o
[ 24%] Building C object librabbitmq/CMakeFiles/rabbitmq-static.dir/amqp_hostcheck.c.o
[ 24%] Linking C static library librabbitmq.a
[ 24%] Built target rabbitmq-static
Scanning dependencies of target amqp_consumer
[ 25%] Building C object examples/CMakeFiles/amqp_consumer.dir/amqp_consumer.c.o
[ 26%] Building C object examples/CMakeFiles/amqp_consumer.dir/utils.c.o
[ 27%] Building C object examples/CMakeFiles/amqp_consumer.dir/unix/platform_utils.c.o
[ 28%] Linking C executable amqp_consumer
[ 28%] Built target amqp_consumer
Scanning dependencies of target amqp_listenq
[ 28%] Building C object examples/CMakeFiles/amqp_listenq.dir/amqp_listenq.c.o
[ 29%] Building C object examples/CMakeFiles/amqp_listenq.dir/utils.c.o
[ 30%] Building C object examples/CMakeFiles/amqp_listenq.dir/unix/platform_utils.c.o
[ 31%] Linking C executable amqp_listenq
[ 31%] Built target amqp_listenq
Scanning dependencies of target amqp_connect_timeout
examples/CMakeFiles/amqp_connect_timeout.dir/depend.make:4: *** missing separator.  Stop.
CMakeFiles/Makefile2:289: recipe for target 'examples/CMakeFiles/amqp_connect_timeout.dir/all' failed
make[1]: *** [examples/CMakeFiles/amqp_connect_timeout.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alekseYY** [comment]
ADDITION: Everything works OK on my other VM, which has older configuration:

OS: Linux ubuntu8 3.19.0-66-generic #74~14.04.1-Ubuntu SMP Tue Jul 19 19:56:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alanxz** [comment]
You can disable examples by `-DBUILD_EXAMPLES=OFF`

Looks like something is screwy with cmake or gcc on that system.

What version of `cmake`, `make`, and `gcc` are you running? When running cmake the first time, what sort of output did you get?

**Comment by alekseYY** [comment]
user@ubuntu:~$ cmake --version
cmake version 3.5.1

user@ubuntu:~$ make --version
GNU Make 4.1
Built for x86_64-pc-linux-gnu

user@ubuntu:~$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

user@ubuntu:~/rabbitmq-c-0.8.0/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_BUILD_TYPE not specified. Creating Release build
-- Found C inline keyword: inline
-- Looking for getaddrinfo
-- Looking for getaddrinfo - found
-- Looking for socket
-- Looking for socket - found
-- Looking for htonll
-- Looking for htonll - not found
-- Looking for poll
-- Looking for poll - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for posix_spawnp in rt
-- Looking for posix_spawnp in rt - found
-- Performing Test HAVE_GNU90
-- Performing Test HAVE_GNU90 - Success
-- Could NOT find POPT (missing:  POPT_INCLUDE_DIR POPT_LIBRARY) 
-- Could NOT find XMLTO (missing:  XMLTO_EXECUTABLE) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "1.0.2g", minimum required is "0.9.8") 
-- Building rabbitmq as a shared library - yes
-- Building rabbitmq as a static library - yes
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/rabbitmq-c-0.8.0/build

**Comment by alekseYY** [comment]
@alanxz: Thank you, examples switching off has helped me.

Interestingly - I have the same problem ("missing separator") when I try to build the "SimpleAmqpClient" package

**Comment by alanxz** [comment]
What do the first few lines of "examples/CMakeFiles/amqp_connect_timeout.dir/depend.make" look like (maybe first 10 lines) look when it fails?

**Comment by alekseYY** [comment]
That's the complete file "examples/CMakeFiles/amqp_connect_timeout.dir/depend.make" (empty lines are empty, i.e there are no tabs there):

# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

examples/CMakeFiles/amqp_connect_timeout.dir/amqp_connect_timeout.c.o: ../librabbitmq/amqp.h
examples/CMakeFiles/amqp_connect_timeout.dir/amqp_connect_timeout.c.o: ../librabbitmq/amqp_framing.h
examples/CMakeFiles/amqp_connect_timeout.dir/amqp_connect_timeout.c.o: ../librabbitmq/amqp_tcp_socket.h
examples/CMakeFiles/amqp_connect_timeout.dir/amqp_connect_timeout.c.o: ../examples/amqp_connect_timeout.c
examples/CMakeFiles/amqp_connect_timeout.dir/amqp_connect_timeout.c.o: ../examples/utils.h

examples/CMakeFiles/amqp_connect_timeout.dir/unix/platform_utils.c.o: ../examples/unix/platform_utils.c

examples/CMakeFiles/amqp_connect_timeout.dir/utils.c.o: ../librabbitmq/amqp.h
examples/CMakeFiles/amqp_connect_timeout.dir/utils.c.o: ../librabbitmq/amqp_framing.h
examples/CMakeFiles/amqp_connect_timeout.dir/utils.c.o: ../examples/utils.c
examples/CMakeFiles/amqp_connect_timeout.dir/utils.c.o: ../examples/utils.h

**Comment by alekseYY** [comment]
I don't know how to disable GitHub markdown, so lines, starting with hash, became "h1" headers

**Comment by alanxz** [comment]
Surround the text you want treated like code with ``` on the line before/after and markdown will treat it like code.

**Comment by alanxz** [comment]
This really looks like a bug in CMake. Could you try installing a newer version of CMake on the system where it doesn't work, and see if you have the same issue?

**Comment by alanxz** [comment]
This hasn't been updated in a while. Please re-open if this is still an issue.
