### ISSUE TITLE
Incorrect return code in amqp_ssl_socket_recv

### ISSUE THREAD

**Issue by mrhazaf** [alanxz/rabbitmq-c#395]
In version 0.8, when I use the function amqp_simple_wait_frame_noblock, I got a AMQP_STATUS_SSL_ERROR intermittently. I believe there is a bug there as this behavior hasn't been noticed with version 0.5.
I did some troubleshooting and when I call WSAGetLastError, I got WSAEWOULDBLOCK, so this has been introduced since the non-blocking sockets.
In the function amqp_ssl_socket_recv, there is a missing part to check the error code as implemented in amqp_tcp_socket_recv (line 143-160). The same logic has to be implemented with SSL sockets as well.

**Comment by alanxz** [comment]
[`amqp_ssl_socket_recv`](https://github.com/alanxz/rabbitmq-c/blob/b1acb373661a9a799428b50fa402be231013e374/librabbitmq/amqp_openssl.c#L145) currently does attempt to handle the results of OpenSSL [`SSL_read()`](https://linux.die.net/man/3/ssl_read) according to the docs.  IIUC the library code should only test for readability/writability of the socket in the way OpenSSL wants it.

Could you tell me which version of OpenSSL you've compiled against, and which MSVC platform you're compiled against and running on?

**Comment by mrhazaf** [comment]
I've compiled with OpenSSL version 1.0.2 on Visual Studio 2015 (v140).
According to [SSL_read()](https://linux.die.net/man/3/ssl_read) documentation, if the return value is negative, [SSL_get_error()](https://linux.die.net/man/3/ssl_get_error) would give more information on the error. If _SSL_get_error_ returns _SSL_ERROR_SYSCALL_, then it's an I/O error and in this situation you can check errno on Linux or [WSAGetLastError](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx) on Windows to find out the reason.
On Windows, _SSL_read_ could cause a _WSAEWOULDBLOCK_ error because no data is queued to be read from the socket.

**Comment by alanxz** [comment]
`SSL_read` will return `SSL_ERROR_WANT_READ` or `SSL_ERROR_WANT_WRITE` if a `read` or `write` on a socket returns an `WSAEWOULDBLOCK` error.  See the error-path in [OpenSSL bss_sock.c](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/crypto/bio/bss_sock.c#L134).  `SSL_read` may read **or write** to a socket, if the library looks for a WSAEWOULDBLOCK condition, its not clear whether the library would need to wait for the socket to be readable or writeable.

You might be able to get more information about what is going on by adding some additional logging in `amqp_openssl.c`.

**Comment by alanxz** [comment]
This bug hasn't been updated in a while, please re-open if this is still an issue.
