### ISSUE TITLE
{writer,send_failed,{error,timeout}} and {inet_error,enotconn}

### ISSUE THREAD

**Issue by ikiranreddy** [alanxz/rabbitmq-c#400]
Hi All,

I am getting below error in rabbitmq log file when the connection got droped from rabbimq-c.
I am using centos 7 with rabbitmq-server-3.6.5-1. I am facing this problem when consuming messages from rabbitmq queue.

Can some one help me how to resolve this below issue.

ERROR in rabbimq-c
-----------------------------------
AMQP_STATUS_SOCKET_ERROR: A socket error occurred

EROR in Rabbitmq-server
-----------------------------------
=ERROR REPORT==== 3-Feb-2017::00:22:30 ===
closing AMQP connection <0.8402.0> (127.0.0.1:59370 -> 127.0.0.1:5672):
{writer,send_failed,{error,timeout}}

=ERROR REPORT==== 3-Feb-2017::13:54:41 ===
closing AMQP connection <0.26131.12> (127.0.0.1:38632 -> 127.0.0.1:5672):
{inet_error,enotconn}

Thanks and Regards,
Kiran Reddy

**Comment by alanxz** [comment]
It means the underlying TCP connection between the client and the broker has terminated.  You should create a new amqp_connection_state_t object and re-connect to the broker.
