### ISSUE TITLE
Is there a "proper" way to time-out RPC calls?

### ISSUE THREAD

**Issue by emarcotte** [alanxz/rabbitmq-c#403]
Howde,

I'm working in an environment where I want to have everything -- I want publish confirmation, and I want to quickly give up if there is RabbitMQ latency. As a result, when a new client connects I need to:

1. open socket
2. login
3. confirm_select
4. publish
5. wait for confirmation

I've managed to use the stuff from https://github.com/alanxz/rabbitmq-c/issues/300 to get 1 and 2 timing out when there are issues (at least in my basic tests).

Publish seems to be write-only, so I haven't really spent much time looking at that, and my wait for confirmation logic is (mostly) catching scenarios when rabbit is being sluggish. 

That just leaves me with the confirm call. I don't have any strong evidence to suggest that rabbit is ever sluggest to respond to it, but I would like to make sure I try to get as much coverage as possible for operations that can block.

It seems that the main RPC functions don't take timeouts. I haven't done the work yet, but I think it would be possible to re-implement `amqp_simple_rpc` on my end to pass a timeout into (ultimately) `wait_frame_inner`. This seems somewhat unnatural though, so I wanted to double check that I wasn't missing something.

Would patches to add timeout support to RPC functions be useful? If so, are there any notes on what the preferable API might look like?

**Comment by alanxz** [comment]
In general I'm not willing to add a timeout to RPC functions.  The main issue with adding a timeout to RPC functions is that AMQP is a state-full protocol, if a client decides that an RPC has timed out, there's no mechanism for informing the broker to abandon the RPC, the best a client can do is to close the connection.  This already exists as a features of the protocol: [heartbeats](https://www.rabbitmq.com/heartbeats.html), which can be used to detect dead-clients, dead-brokers, or issues with connectivity.  This is enabled by passing a positive number for the `heartbeat` parameter of `amqp_login`. 

FYI: the implementation of a timeout for `amqp_login` in #300 works for 2 reasons: 1) there's a very clear state transition - if `amqp_login` times out - the connection should be closed, 2) the RabbitMQ broker has similar behavior: if the login-handshake doesn't complete within a few seconds, it closes the connection.

**Comment by zbentley** [comment]
But how would a client decide to close the connection, or even break out of the RPC at all, detect a timeout? Is the only option to spin up a separate thread and issue hard-interrupting kills from there? That seems like a lot of coordination work and overhead when `select` is available to single-threaded clients already.

**Comment by alanxz** [comment]
@zbentley heartbeats are handled by the library.  If a heartbeat timeout occurs the the RPC (or any call that blocks on a network read or write) will fail with `AMQP_STATUS_HEARTBEAT_TIMEOUT`, and at that point the connection is considered closed, this can all be done from a single thread.

Unfortunately the current design of rabbitmq-c does not lend itself to allowing non-library code to manage the underly socket.

**Comment by alanxz** [comment]
Thanks for the detailed explanation, your use-case makes a bit more sense to me now.

In this case heartbeats really aren't the right solution: they're not dynamically configurable. Additionally both the client and the server must service the heartbeat regularly; given rabbitmq-c's single-threaded design - they're only serviced during library calls, so executing non-rabbitmq-c code for hours won't work in this case (the broker will likely drop the connection). As an aside - I'm impressed that you can get a TCP connection with no traffic on it to stay up for 10 hours.

I can see a case for adding an option to set a timeout on an AMQP RPC calls, with the idea that if the RPC times out the connection is considered failed, and is closed. If I were to do this - it'd be implemented in a similar fashion to how the timeout for `amqp_login` is implemented, with a separate function that sets the RPC timeout for the connection; which makes it less likely to be used at all. This does add a bit of complexity to an API that is already a bit messy.  I'll try implementing this and see if I can make this something that works.

**Comment by alanxz** [comment]
@zbentley take a look at the branch in #404, and see if that does what you need it to do.
