### ISSUE TITLE
Multithreaded connection pool

### ISSUE THREAD

**Issue by arossert** [alanxz/rabbitmq-c#406]
I'm using rabbitmq-c in a multithreaded application and I have implemented a "connection pool" using boost::lockfree::queue like so:

`boost::lockfree::queue<amqp_connection_state_t> connections_pool;`

Every time a thread needs to communicate with the rabbitmq server, he checks the "pool" (try to pop from the queue) for a free connection, if no connections were found, he open a new connection, use it and adding the connection to the pool.
This way I can guarantee that a connection will be used only by one thread at a time.

Is this a good design?
Is a connection can be opened in one thread and used in another?

**Comment by alanxz** [comment]
Its hard to comment on the design without understanding more about what your application and what its requirements are.

Yes, an amqp_connection_state_t may be created in one thread and used in another as long as accesses to the object are synchronized.

FYI: this sort of question is better handled on the discussion email list [rabbitmq-c-users](https://groups.google.com/forum/#!forum/rabbitmq-c-users).
