### ISSUE TITLE
Missing some dependency library?

### ISSUE THREAD

**Issue by focaaby** [alanxz/rabbitmq-c#407]
I just installed Ubuntu 16.04.02 server, after following these steps:

```
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install autoconf automake libtool pkg-config
```
lib version:
autoconf (GNU Autoconf) 2.69
automake (GNU automake) 1.15
libtoolize (GNU libtool) 2.4.6
pkg-config 0.29.1
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

rabbitmq-c version:  v0.8.0+

download this [sample code](https://github.com/robomq/robomq.io/blob/master/sdk/AMQP/C/request-reply/consumer.c)

`$ gcc consumer.c -o consumer -L/usr/local/lib -lrabbitmq -Wall`

```
$ ldd consumer
	linux-vdso.so.1 =>  (0x00007ffe83cef000)
	librabbitmq.so.4 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff3a8fb1000)
	/lib64/ld-linux-x86-64.so.2 (0x000055bfce66c000)
```

```
$ ll /usr/local/lib
total 444
drwxr-xr-x  4 root root    4096 Mar 15 12:35 ./
drwxr-xr-x 10 root root    4096 Mar  5 21:34 ../
-rwxr-xr-x  1 root root     948 Mar 15 12:35 librabbitmq.la*
lrwxrwxrwx  1 root root      20 Mar 15 12:35 librabbitmq.so -> librabbitmq.so.4.2.0*
lrwxrwxrwx  1 root root      20 Mar 15 12:35 librabbitmq.so.4 -> librabbitmq.so.4.2.0*
-rwxr-xr-x  1 root root  432472 Mar 15 12:35 librabbitmq.so.4.2.0*
drwxr-xr-x  2 root root    4096 Mar 15 12:35 pkgconfig/
drwxrwsr-x  3 root staff   4096 Mar  5 21:34 python3.5/
```

After installing `libcwidget3v5`, then recompiled `rabbitmq-c` and `consumer.c` code

```
$ sudo apt-get install libcwidget3v5
$ ldd consumer
	linux-vdso.so.1 =>  (0x00007ffebe1b6000)
	librabbitmq.so.4 => /usr/local/lib/librabbitmq.so.4 (0x00007f12b1ad4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f12b170b000)
	/lib64/ld-linux-x86-64.so.2 (0x000055e59ea4c000)
```

Is there missing some dependency library?

**Comment by alanxz** [comment]
Its unclear to me why installing libcwidget3v5 would cause the dynamic linker to find the rabbitmq-c library.  Make sure that /usr/local/lib is in a path where the shared linker will find it (try adding `/usr/local/lib` to your `LD_LIBRARY_PATH` environment variable, or set [`LD_DEBUG`](http://man7.org/linux/man-pages/man8/ld.so.8.html) to `libs`.
