### ISSUE TITLE
connection lost after day for setting up Rabbitmq-server

### ISSUE THREAD

**Issue by nijojames92** [alanxz/rabbitmq-c#416]
Hi 

I've setup Rabbitmq as broker for my celery tasks which processes 2600000 data. But i'm lossing connection to rabbitmq server after a day of running the tasks.

ERROR/MainProcess] consumer: Cannot connect to amqp://user:**@ip:5672/vhost: [Errno 111] Connection refused.
Trying again in 32.00 seconds..

I was not able to restart the rabbitmq process. I'm not sure why. I have manually kill all the rabbit mq process and reinstall rabbitmq-server everyday to run the celery tasks

Can you guys help me with this

**Comment by alanxz** [comment]
rabbitmq-c is a client library for the RabbitMQ broker.  This sounds like you're having trouble with the broker as opposed to a client in particular.  You'll have better luck asking on the [rabbitmq-users mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users).
