### ISSUE TITLE
./configure and pk-config

### ISSUE THREAD

**Issue by jakeisabear** [alanxz/rabbitmq-c#419]
Looking for a little advice here as to where I am going wrong.

I have followed the steps at alanxz.github.io/rabbitmq-c/ to get this running on my debian VM. I am running into a problem I have seen a couple places on the web. I get the following error when running ./configure:

`./configure: line 12655: syntax error near unexpected token '0.17'`
`./configure: line 12655: 'PKG_PROG_PKG_CONFIG(0.17)'`

I have seen that this would likely be contributed to pkg-config being missing, but I have verified multiple times that it is both installed and up to date. 

I'm suspecting something is not configured properly, so any suggestions of where to look would helpful.

Thanks.

**Comment by alanxz** [comment]
Try the debugging steps here: https://askubuntu.com/questions/468661/how-to-fix-pkg-prog-pkg-config-command-not-found-error

**Comment by jakeisabear** [comment]
Thanks, that didn't wind up being it. After chasing my tail for about 3 hours I realized that once you get the error and go back and install pkg-config, you have to run `autoreconf -i` again before you run `./configure`
