### ISSUE TITLE
basic ack to message relation

### ISSUE THREAD

**Issue by dmitryme** [alanxz/rabbitmq-c#425]
Hello,
is there a way to make a relation between sent message and basic ack received from broker?

**Comment by alanxz** [comment]
Yes, see the description for [publisher confirms](https://www.rabbitmq.com/confirms.html#publisher-confirms).  The relevant bit is:

> Once a channel is in confirm mode, both the broker and the client count messages (counting starts at 1 on the first  confirm.select). The broker then confirms messages as it handles them by sending a  basic.ack on the same channel. The  delivery-tag field contains the sequence number of the confirmed message. The broker may also set the  multiple field in basic.ack to indicate that all messages up to and including the one with the sequence number have been handled.
