### ISSUE TITLE
amqp_consume_message() return AMQP_STATUS_UNEXPECTED_STATE in multithread

### ISSUE THREAD

**Issue by yinch0222** [alanxz/rabbitmq-c#428]
hello

i try to consume messages by using amqp_consume_message() in the main thread, and the child threads  the process the messages and ack by using amqp_basic_ack, but then i have a problem: after running a while, amqp_consume_message() return AMQP_STATUS_UNEXPECTED_STATE and can't get messages any more.

all threads are using the same amqp_connection_state_t, is this because amqp_connection_state_t is not thread-safe?

 who could i to handle this problem?  now, i close the connection and conncet again when AMQP_STATUS_UNEXPECTED_STATE occurs.

Appreciate if you can help me on this.

Thanks

**Comment by alanxz** [comment]
An `amqp_connection_state_t` object cannot be safely used by multiple threads without synchronization. 

Synchronize access to the connection state object using something like a mutex, and it should work.

**Comment by yinch0222** [comment]
thanks a lot for your suggestion.

**Comment by yinch0222** [comment]
thanks a lot for your help  :）
