### ISSUE TITLE
Heartbeat check

### ISSUE THREAD

**Issue by pswcw** [alanxz/rabbitmq-c#433]
Hi,
   I am using 0.8.0 of rabbitmq-c client. How have I a heartbeat sent to or received from the rabbitmq server without publishing or consuming message? Can you give me a example to receive heartbeat from server without consuming message? the parameter of heartbeat set to 3s have been passed to amqp_login(), and I  want to check heartbeat to see whether the connection to server has been closed.

**Comment by alanxz** [comment]
Calling `amqp_simple_wait_frame` and `amqp_simple_wait_frame_noblock` with some kind of timeout will cause heartbeat messages to be processed, however your code must be prepared to handle message delivery (that is if a `basic.deliver` method is read, you will need to read the rest of the message using `amqp_read_message` or by repeatedly calling `amqp_simple_wait_frame` and constructing the message yourself.
