### ISSUE TITLE
VC_EXTRALEAN required if MS Visual Studio 2017 is installed

### ISSUE THREAD

**Issue by EvilBeaver** [alanxz/rabbitmq-c#453]
After installation of MS Visual Studio 2017 WIN32_LEAN_AND_MEAN flag is not enough.
It also need an VC_EXTRALEAN definition.

I can make a pull-request, but need an advice:

* should I do it with ADD_DEFINITIONS(VC_EXTRALEAN) in cmake file
* or I'd better add VC_EXTRALEAN directly in sources?

**Comment by alanxz** [comment]
Could you describe why `VC_EXTRALEAN` is required (links to msdn documentation would be great!)?

As far as I know `WIN32_LEAN_AND_MEAN` just includes less stuff, making builds a bit faster, I don't think its actually required to successfully build on Win32 (I could be wrong).

**Comment by EvilBeaver** [comment]
I have no idea why VC_EXTRALEAN helped. Finally, I've updated Windows SDK and problem's gone. No VC_EXTRALEAN required anymore
