### ISSUE TITLE
QUESTION: Does library support Tx (transactions) class?

### ISSUE THREAD

**Issue by EvilBeaver** [alanxz/rabbitmq-c#455]
AMQP supports transactions logic https://www.rabbitmq.com/amqp-0-9-1-reference.html#class.tx

Can we use it with rabbitmq-c?

**Comment by alanxz** [comment]
Yes rabbitmq-c does support transactions, use the [`amqp_tx_select`](https://github.com/alanxz/rabbitmq-c/blob/550f4c56562baf2dc1c6c6b6285b4fd13fa0097c/librabbitmq/amqp_framing.h#L959), `amqp_tx_commit` and `amqp_tx_rollback` functions to manage AMQP transactions.
