### ISSUE TITLE
amqp_consume_message returns AMQP_RESPONSE_LIBRARY_EXCEPTION

### ISSUE THREAD

**Issue by reddysrikesh** [alanxz/rabbitmq-c#456]
We are using rabbitmq-c v0.7.0.2. amqp_consume_message works fine when number of ready messages in queue is small. If publisher publishes 25000 messages, consumer is running into AMQP_RESPONSE_LIBRARY_EXCEPTION after consuming ~10000 messages. amqp_basic_consume returns: {reply_type = AMQP_RESPONSE_LIBRARY_EXCEPTION, reply = {id = 0, decoded = 0x0}, library_error = -2}. What does library_error -2 mean? How should we handle this error case?

**Comment by alanxz** [comment]
`library_error` is a [`amqp_status_enum`](https://github.com/alanxz/rabbitmq-c/blob/550f4c56562baf2dc1c6c6b6285b4fd13fa0097c/librabbitmq/amqp.h#L686) value.  -2 in this case means that the library received a corrupted frame on the network.  

In this case you need to terminate the connection and open a new one.

FYI: you can get an error string by calling [`amqp_error_string2`](https://github.com/alanxz/rabbitmq-c/blob/550f4c56562baf2dc1c6c6b6285b4fd13fa0097c/librabbitmq/amqp.h#L2090) with the code.

**Comment by reddysrikesh** [comment]
Thanks alanxz. It worked!

**Comment by reddysrikesh** [comment]
Our program seg faulted with three different backtraces when we are trying to close channel in this case(AMQP_STATUS_BAD_AMQP_DATA).

#0  0x00007ffff58df45d in amqp_socket_recv (self=0x622d376531312d38, buf=0x3065333133646164, len=7076905863073654374, flags=0)
    at tmp/rabbitmq-c-0.7.0/librabbitmq/amqp_socket.c:216
#1  0x00007ffff58e0205 in recv_with_timeout (state=0x7fff680d0b40, timeout=...) at tmp/rabbitmq-c-0.7.0/librabbitmq/amqp_socket.c:701
#2  0x00007ffff58e05a2 in wait_frame_inner (state=0x7fff680d0b40, decoded_frame=0x7fff637fc5b0, timeout=0x0) at tmp/rabbitmq-c-0.7.0/librabbitmq/amqp_socket.c:836
#3  0x00007ffff58e0c89 in amqp_simple_rpc (state=0x7fff680d0b40, channel=1, request_id=1310760, expected_reply_ids=0x7fff637fc670, decoded_request_method=0x7fff637fc650)
    at tmp/rabbitmq-c-0.7.0/librabbitmq/amqp_socket.c:1062
#4  0x00007ffff58dd65a in amqp_channel_close (state=0x7fff680d0b40, channel=1, code=200) at tmp/rabbitmq-c-0.7.0/librabbitmq/amqp_api.c:281
#5  0x0000000000595405 in RabbitMQClient::RMQDisconnect (this=0x7fff7008a9a0) at RabbitMQClient.cpp:314

#1  0x00007ffff58de072 in consume_data (state=0x7fff70089d90, received_data=0x7fff637fc458) at tmp/rabbitmq-c-0.7.0/librabbitmq/amqp_connection.c:236
#2  0x00007ffff58de132 in amqp_handle_input (state=0x7fff70089d90, received_data=..., decoded_frame=0x7fff637fc5b0) at tmp/rabbitmq-c-0.7.0/librabbitmq/amqp_connection.c:264
#3  0x00007ffff58e0191 in consume_one_frame (state=0x7fff70089d90, decoded_frame=0x7fff637fc5b0) at tmp/rabbitmq-c-0.7.0/librabbitmq/amqp_socket.c:685
#4  0x00007ffff58e04a8 in wait_frame_inner (state=0x7fff70089d90, decoded_frame=0x7fff637fc5b0, timeout=0x0) at tmp/rabbitmq-c-0.7.0/librabbitmq/amqp_socket.c:799
#5  0x00007ffff58e0c89 in amqp_simple_rpc (state=0x7fff70089d90, channel=1, request_id=1310760, expected_reply_ids=0x7fff637fc670, decoded_request_method=0x7fff637fc650)
    at tmp/rabbitmq-c-0.7.0/librabbitmq/amqp_socket.c:1062
#6  0x00007ffff58dd65a in amqp_channel_close (state=0x7fff70089d90, channel=1, code=200) at tmp/rabbitmq-c-0.7.0/librabbitmq/amqp_api.c:281
#7  0x0000000000595405 in RabbitMQClient::RMQDisconnect (this=0x7fff7008a9a0) at RabbitMQClient.cpp:316

Another bt points to amqp_connection.c: 301
