### ISSUE TITLE
what to do when connection has error

### ISSUE THREAD

**Issue by applecandyfromsky** [alanxz/rabbitmq-c#460]
I see code in example like this:

   ret = amqp_consume_message(conn, &envelope, NULL, 0);

    if (AMQP_RESPONSE_NORMAL != ret.reply_type) {
      if (AMQP_RESPONSE_LIBRARY_EXCEPTION == ret.reply_type &&
          AMQP_STATUS_UNEXPECTED_STATE == ret.library_error) {
        if (AMQP_STATUS_OK != amqp_simple_wait_frame(conn, &frame)) {
          return;
        }

        if (AMQP_FRAME_METHOD == frame.frame_type) {
          switch (frame.payload.method.id) {
            case AMQP_BASIC_ACK_METHOD:
              /* if we've turned publisher confirms on, and we've published a message
               * here is a message being confirmed
               */

              break;
            case AMQP_BASIC_RETURN_METHOD:
              /* if a published message couldn't be routed and the mandatory flag was set
               * this is what would be returned. The message then needs to be read.
               */
              {
                amqp_message_t message;
                ret = amqp_read_message(conn, frame.channel, &message, 0);
                if (AMQP_RESPONSE_NORMAL != ret.reply_type) {
                  return;
                }

                amqp_destroy_message(&message);
              }

              break;

            case AMQP_CHANNEL_CLOSE_METHOD:
              /* a channel.close method happens when a channel exception occurs, this
               * can happen by publishing to an exchange that doesn't exist for example
               *
               * In this case you would need to open another channel redeclare any queues
               * that were declared auto-delete, and restart any consumers that were attached
               * to the previous channel
               */
              return;

            case AMQP_CONNECTION_CLOSE_METHOD:
                printf("conn closed\n");
              /* a connection.close method happens when a connection exception occurs,
               * this can happen by trying to use a channel that isn't open for example.
               *
               * In this case the whole connection must be restarted.
               */
              return;

            default:
              fprintf(stderr ,"An unexpected method was received %u\n", frame.payload.method.id);
              return;
          }
        }
      }

    } else {
      amqp_destroy_envelope(&envelope);
    }

But sometimes,when I shutdown the mq server,the ret.library_error is not AMQP_STATUS_UNEXPECTED_STATE but AMQP_STATUS_CONNECTION_CLOSED or  AMQP_STATUS_SOCKET_ERROR,
Using this code,my client still think the connection is ok and run.

Should I write like this?
if (AMQP_RESPONSE_NORMAL != ret.reply_type) {
      if (AMQP_RESPONSE_LIBRARY_EXCEPTION == ret.reply_type &&
          AMQP_STATUS_UNEXPECTED_STATE == ret.library_error) {
     ......
      }
      else {
      if(ret.library_error == AMQP_STATUS_CONNECTION_CLOSED  || ret.library_error==AMQP_STATUS_SOCKET_ERROR ){
         .......
          //close the connection
           }
        }
}

**Comment by alanxz** [comment]
Yes - if you get an `AMQP_STATUS_CONNECTION_CLOSED` or `AMQP_STATUS_SOCKET_ERROR` that means the `amqp_connection_state_t` is in a failed state. You will need to destroy the `amqp_connection_state_t` object and restart the connection.

**Comment by applecandyfromsky** [comment]
Thanks,so besides  AMQP_STATUS_CONNECTION_CLOSED or AMQP_STATUS_SOCKET_ERROR,is there any other case I should handle?

**Comment by alanxz** [comment]
The current list of error codes can be [found here](https://github.com/alanxz/rabbitmq-c/blob/bd7c497e5d1a1924661df2190d3c38f11add5b2b/librabbitmq/amqp.h#L691). 

The most robust thing to do is to validate functions that return an `int` by checking for an `AMQP_STATUS_OK` value. Anything else is an error.  For functions that return an `amqp_rpc_reply_t`, check for an `reply_type == AMQP_RESPONSE_NORMAL`, anything else is an error. For functions that return a pointer (e.g., amqp_queue_declare), if the function returns `NULL`, assume that the function has failed.  `amqp_get_rpc_reply` can get the error in this case.

**Comment by applecandyfromsky** [comment]
But  AMQP_STATUS_TIMEOUT means there is no message in the queue,not an actual error.Right?
So I think I should exclude it .

**Comment by alanxz** [comment]
That is correct

**Comment by applecandyfromsky** [comment]
Thanks.
