### ISSUE TITLE
install php-amqp extension fails:notice:'amqp_ssl_socket.h' file not found

### ISSUE THREAD

**Issue by shenboran** [alanxz/rabbitmq-c#463]
Hi,I'm macOX user! my openssl version is LibreSSL 2.2.7
after 
`./configure --prefix=/usr/local/rabbitmq-c-0.8.0`

show it:
rabbitmq-c build options:
    Host: x86_64-apple-darwin17.2.0
    Version: 0.8.0
    SSL/TLS: no // **I wonder it is problem,but i don't know how to fix it**
    Tools: no
    Documentation: no
    Examples: yes

then 
`sudo pecl install http://pecl.php.net/get/amqp-1.9.3.tgz`
but show 
`libs/amqp_connection_resource.o
/private/tmp/pear/temp/amqp/amqp_connection_resource.c:45:10: fatal error: 'amqp_ssl_socket.h' file not found
`
i don't know how to fix      rabbitmq-c build options: SSL/TLS:openssl

**Comment by alanxz** [comment]
rabbitmq-c is not tested with LibreSSL, so if there are differences in API between OpenSSL v1.0.1 and LibreSSL v2.2.7 this may not work.

Likely the issue is that autotools cannot find LibreSSL.  Try using CMake to compile rabbitmq-c, you may need to add `-DOPENSSL_ROOT_DIR=/path/to/libressl` to the cmake command line.

**Comment by shenboran** [comment]
3Q,I fixed the problem

**Comment by Joseph-Alice** [comment]
大佬，您是怎么解决这个问题的？我也遇到了这个问题，求指教！
![image](https://user-images.githubusercontent.com/20185276/38605887-242b59d8-3da7-11e8-93db-2efea0dd0c4a.png)

**Comment by blueseashore** [comment]
先安装rabbitmq-c,然后再编译amqp.so
如果在编译amqp.so时，提示缺少amqp_ssl_socket.h，可以从rabbitmq-c里把该文件拷贝过去，重新make && make install 就可以

**Comment by sjz05000** [comment]
@blueseashore 解决了。谢谢了

**Comment by CFrank227** [comment]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/amqp.so' - /usr/lib64/php/modules/amqp.so: undefined symbol: amqp_ssl_socket_set_verify_hostname in Unknown on line 0

这个问题有哪个大佬知道是咋回事儿嘛 - -

**Comment by Tmtlihu** [comment]
> PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/amqp.so' - /usr/lib64/php/modules/amqp.so: undefined symbol: amqp_ssl_socket_set_verify_hostname in Unknown on line 0
> 
> 这个问题有哪个大佬知道是咋回事儿嘛 - -

I met it. I recompiled it
