### ISSUE TITLE
Respect HB timeouts on amqp_login.

### ISSUE THREAD

**Issue by raydre** [alanxz/rabbitmq-c#467]
We recently had a network issue with a switch. What we observed is that some of our processes were hanging during what looked like an application reconnect. We managed to reproduce similar behaviour, and it looks like the initial AMQP handshake is not protected by a timeout. 

We are not certain it is exactly what happened. However, to insulate ourselves from these types of failures, we would like to have this addressed in the library.  We cannot see a way to protect ourselves in the application layer. 
I am happy to submit a pull request if you think this is reasonable request.

**Comment by alanxz** [comment]
You probably want to use the [`amqp_set_handshake_timeout`](https://github.com/alanxz/rabbitmq-c/blob/b80de27b8782772dfb3fe8253940663697f680ee/librabbitmq/amqp.h#L2448) function which does what you're describing.

**Comment by raydre** [comment]
Thanks for that.  

We were looking at your 0.8.0 tag, which we assume is your release tag. What is your release procedure? Will you be doing another release soon?

**Comment by alanxz** [comment]
Next release will be v0.9.0, and I'm targeting end of January-2018 as a release date.

**Comment by raydre** [comment]
Is it possible, we could get an early release tag? Something that will be very close to your actual release tag.   

We hit this issue in production and we currently still exposed. 

Your help will be very much appreciated.
