### ISSUE TITLE
Error at amp_login

### ISSUE THREAD

**Issue by roderick1980** [alanxz/rabbitmq-c#490]
Hi,
I've got the following error while executing examples "amqp_bind" and "amqp_listen", when calling 'amqp_login' function:
_"Logging in: server connection errror 403h, message: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. for details see the broker logfile. "_
Please, can anybody help me with this? Is there any log file I can read and where?

Thanks in advance

**Comment by roderick1980** [comment]
Hi,
I've noticed that everything works ok under my host machine.
I was executing under guest machine (Virtual Box).
However, it should work....

**Comment by alanxz** [comment]
It sounds like you're trying to use the guest/guest username/password - which by default is only enabled to login from `localhost`. Make sure you have the correct authentication information when connecting to the broker. See [this doc](https://www.rabbitmq.com/access-control.html) on how to set that up.
