### ISSUE TITLE
fatal error LNK1104: cannot open file 'rt.lib'

### ISSUE THREAD

**Issue by Iamthegeekdavid** [alanxz/rabbitmq-c#510]
hi there, I am looking for help in installing rabbitmq-c on Windows 10.

I am building rabbitmq-c on my desktop Windows system.
System: windows 10, 64bit 
Compiler: MSVS 2017(visual studio 15, 64bit)
Cmake: 3.9.6

when configuring in cmake, an error occurred. CMake displayed the following error. It looks like that I need to install OpenSSL.
####################################################################
The C compiler identification is MSVC 19.12.25835.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.12.25827/bin/Hostx86/x64/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.12.25827/bin/Hostx86/x64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Found C inline keyword: inline
Looking for poll
Looking for poll - not found
Looking for clock_gettime in rt
Looking for clock_gettime in rt - not found
Looking for posix_spawnp in rt
Looking for posix_spawnp in rt - not found
CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR) (Required is at least version "0.9.8")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.9/Modules/FindOpenSSL.cmake:388 (find_package_handle_standard_args)
  CMakeLists.txt:122 (find_package)

Configuring incomplete, errors occurred!
See also "E:/Staff/trash/message/rabbitmq-c/build/CMakeFiles/CMakeOutput.log".
See also "E:/Staff/trash/message/rabbitmq-c/build/CMakeFiles/CMakeError.log".
####################################################################

The log file below indicates that it is due to "cannot find rt.lib".
[CMakeError.log](https://github.com/alanxz/rabbitmq-c/files/2069446/CMakeError.log)

I am confused what to do next. Shall I install OpenSSL or find rt.lib? Google does not tell what rt.lib is.
Thanks,

Wei

**Comment by Iamthegeekdavid** [comment]
Installed OpenSSL and rabbitmq-c was successfully compiled.

**Comment by boskjoett** [comment]
So I guess it is wrong that the README.md file says that OpenSLL is optional.
