### ISSUE TITLE
channel_max set to unlimited bug

### ISSUE THREAD

**Issue by VladislavPershin** [alanxz/rabbitmq-c#513]
@alanxz , HI!

I use your lib in my programm and i got the new exception:
root@host:~/performance-helper/# ./qqqq -r -a -f ~/date_from_queue -q queue_name
exception: open: a socket error occurred.

I have traceback in /var/log/rabbitmq/
```
2018-06-05 05:19:54.171 [info] <0.3073.0> accepting AMQP connection <0.3073.0> (127.0.0.1:41252 -> 127.0.0.1:5672)
2018-06-05 05:19:57.173 [warning] <0.3073.0> closing AMQP connection <0.3073.0> (127.0.0.1:41252 -> 127.0.0.1:5672):
{handshake_error,tuning,0,{exit,{amqp_error,not_allowed,"negotiated channel_max = 0 is higher than the maximum allowed value (2047)",'connection.tune'},'connection.tune_ok',[{rabbit_misc,protocol_error,1,[{file,"src/rabbit_misc.erl"},{line,304}]},{rabbit_reader,handle_method0,2,[{file,"src/rabbit_reader.erl"},{line,1147}]},{rabbit_reader,handle_method0,3,[{file,"src/rabbit_reader.erl"},{line,1100}]},{rabbit_reader,handle_input,3,[{file,"src/rabbit_reader.erl"},{line,1015}]},{rabbit_reader,recvloop,4,[{file,"src/rabbit_reader.erl"},{line,461}]},{rabbit_reader,run,1,[{file,"src/rabbit_reader.erl"},{line,443}]},{rabbit_reader,start_connection,4,[{file,"src/rabbit_reader.erl"},{line,362}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}
```

If we go to https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.5 we saw:
ctrl+F  "max number of channels allowed on a connection":

```
Default max number of channels allowed on a connection (a.k.a. channel_max) has been lowered from 65535 to 2047.
The new default is much safer and will reduce the effect application channel leaks have on node resource consumption. This is a potentially breaking change.

Systems where a lot (at least hundreds) of channels per connection are used should explicitly override channel_max in the config file to a higher suitable value, e.g.:

channel_max = 4000
```

But you set `channel_max` in 0(unlimited):
https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp.h#L337
https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp_connection.c#L141
https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp_connection.c#L85

Can you fix it please?

**Comment by alanxz** [comment]
I'm a bit surprised this new limit causes failures when connecting with the rabbitmq-c client.  Currently the client picks `min(broker_max_channels, client_max_channels)` when [tuning the connection during handshake](https://github.com/alanxz/rabbitmq-c/blob/a65c64c0efd883f3e200bd8831ad3ca066ea523c/librabbitmq/amqp_socket.c#L1393-L1406).  I'd expect the broker to advertise a max-channels, so that the client would follow it.

I will update the default to something smaller.
