### ISSUE TITLE
Incorrect comment in amqp_basic_get?

### ISSUE THREAD

**Issue by jeking3** [alanxz/rabbitmq-c#514]
See: https://github.com/alanxz/rabbitmq-c/blob/acks_examples/librabbitmq/amqp.h#L1984

``* \param [in] no_ack if true the message is automatically ack'ed``

Wouldn't true here mean the message should NOT automatically be acked?

**Comment by jeking3** [comment]
Also if you do not ack here, I don't see a code path that would allow you to ack later.  `amqp_basic_get` does not return a delivery_tag, nor does the follow-up API `amqp_read_message`.

**Comment by alanxz** [comment]
> Wouldn't true here mean the message should NOT automatically be acked?

It means that the client doesn't have to ack the message. See: http://www.rabbitmq.com/amqp-0-9-1-reference.html#domain.no-ack.  I agree that the use of the negative as a parameter name leads to a confusing API.

> Also if you do not ack here, I don't see a code path that would allow you to ack later. `amqp_basic_get` does not return a delivery_tag, nor does the follow-up API `amqp_read_message`.

The delivery tag can be extracted from the `amqp_rpc_reply_t. If `r.reply_type == AMQP_RESPONSE_NORMAL && r.reply.id == AMQP_BASIC_GET_OK_METHOD`, then `r.reply.decoded` can be cast to an `amqp_basic_get_ok_t*`, which has a member `delivery_tag`.
