### ISSUE TITLE
v0.9.0 Tags not merged in Master

### ISSUE THREAD

**Issue by nonifier** [alanxz/rabbitmq-c#524]
Hi, 

Just to let you know that the v0.9.0 tag leaves on it's own on a unnamed branch.
It would be super nice to have the v0.9.0 tag on commit `7e693a2` instead, as it seems to be exactly the same as `77e3805` :)

```
* 1fa5f63 - (8 weeks ago) Fix instructions for default build - Ross Cousens (origin/master, origin/HEAD, master)
* a65c64c - (4 months ago) Bumping revision for development - Alan Antonuk
* 7e693a2 - (4 months ago) Preparation for v0.9.0 release. - Alan Antonuk (HEAD) <-- ? v0.9.0 ?
| * 77e3805 - (4 months ago) Preparation for v0.9.0 release. - Alan Antonuk (tag: v0.9.0)
|/  
* 45067a0 - (5 months ago) Lib: Present "exchange_exchange_bindings" capability to server - Jesus Fernandez Manzano
* db94554 - (4 months ago) Examples: fix argument parsing in sendstring example - jerome
* e1eaaac - (5 months ago) Lib: Add #defines to allow building with LibreSSL - Zane van Iperen
```

Cheers,
Olivier.

**Comment by alanxz** [comment]
Oops, that isn't what I had intended.  

Its a bit hard to change at this point without rewriting history that others have probably already downloaded.  As a compromise, I've added a `v0.9.0-master` tag that points to `7e693a2`.
