### ISSUE TITLE
maybe a bug for non-english letter when read the message form envelope

### ISSUE THREAD

**Issue by guzuomuse** [alanxz/rabbitmq-c#525]
a very strange behavior:
when i read the message from envelope after sent. 
sometimes i got messy code. for example:
when i send message 

> 全部是中文可以？

when read back i got:

> 全部是中文可以？7??

but when a add a Chinese character：

> 全部是中文可以么？

read again, everything goes right:

> 全部是中文可以么？

attention the last Chinese Letter  

> ？

it's the culprit leads to the messy code. same situation is the Chinese letter punctuation mark

> 、

and the Chinese semicolon mark 

> ；

not very time the messy code occurs as i described before.

what need is the explain, i think i have set all my encoding environments go right.

@alanxz 
can you give some suggestion? thank you!

**Comment by alanxz** [comment]
I assume this is going in the body of the message you're sending and receiving.  rabbitmq-c (nor the broker) does not try to interpret the contents of the message body.  The message body is only a string of bytes (which may not be null-terminated).

If you require a null-terminated string, be sure to either include when publishing the message, or add the null-terminator when reading the delivered message.

**Comment by guzuomuse** [comment]
@alanxz ,thanks for your quick reply.
after digging into to the source code, i realize you're right.
the data sent were copied using the memcpy.
if i'm right. maybe i should do manually deal with string data. there is no direct api for getting back string data.
thank you!
