### ISSUE TITLE
How to compile with Position Independent Code?

### ISSUE THREAD

**Issue by waas1919** [alanxz/rabbitmq-c#537]
Hi all

I want to compile this rabbitmq-c as a static library with position independent code (-fPIC / -no-pie) using the CMakeLists.txt and then use the output librabbitmq.a inside a personal shared library (*.so)

What do I need to change on the CMakelLists.txt in order to make this work?

I always get the error when I try to compile my shared library (*.so) that contains the static library from rabbiqmq-c:

[ 50%] Building CXX object CMakeFiles/MyRabbitMq.dir/src/lib/int/rabbitmq.cpp.o
[100%] Linking CXX shared library MyRabbitMq.so
/usr/bin/ld: /var/tmp/src/08af7af7-4618-4131-a64d-e993e1c6e53c/Linux-Release/ext/libs/librabbitmq.a(amqp_framing.c.o): relocation R_X86_64_PC32 against symbol `amqp_empty_bytes' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/MyRabbitMq.dir/build.make:85: recipe for target 'libMyRabbitMq.so' failed

**Comment by EvilBeaver** [comment]
I use this in my CMake

```
set_target_properties(rabbitmq-static PROPERTIES 
          VERSION ${RMQ_VERSION} 
          SOVERSION ${RMQ_SOVERSION} 
          OUTPUT_NAME rabbitmq
          COMPILE_OPTIONS "-fPIC")
```

**Comment by waas1919** [comment]
Thank you EvilBeaver!!!!!
