### ISSUE TITLE
When I Complie a cpp file link SimpleAmqlClient ,it occur like this undefined reference to `amqp_ssl_socket_set_verify_hostname',how can I slove this problem

### ISSUE THREAD

**Issue by ihg1992** [alanxz/rabbitmq-c#539]
g++ recv.cpp -o recv -lSimpleAmqpClient
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libSimpleAmqpClient.so: undefined reference to `amqp_ssl_socket_set_verify_hostname'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libSimpleAmqpClient.so: undefined reference to `amqp_ssl_socket_set_verify_peer'
collect2: error: ld returned 1 exit status

**Comment by EvilBeaver** [comment]
I'm not seeing any linkage to the rabbitmq-c.lib in your command line

**Comment by ihg1992** [comment]
Oh yes ,I got it ,sometimes ago, the target_link_libraries is /usr/lib/x86_64-linux-gnu/librabbitmq.so this time it is in /usr/local/lib/x86_64-linux-gnu/librabbitmq.so ,I change this link file path ,it dose well,thanks so much~
