### ISSUE TITLE
  'AMQ_PLATFORM': undeclared identifier error

### ISSUE THREAD

**Issue by swatinair123** [alanxz/rabbitmq-c#541]
Hi I am trying the build rabbitmq and rabbitmq-static . But i am getting the below error. 

Error	C2065	'AMQ_PLATFORM': undeclared identifier	rabbitmq	e:\rabbitmq-c-master\rabbitmq-c-master\librabbitmq\amqp_socket.c	1337	
Can anyone suggest any suitable soln?

Thanks

**Comment by alanxz** [comment]
`AMQ_PLATFORM` is [defined by CMake](https://github.com/alanxz/rabbitmq-c/blob/75a21e51db5d70ea807473621141b4417d81b56f/cmake/config.h.in#L12)

What platform are you trying to build it on?  What version of CMake are you using?

**Comment by DimShadoWWW** [comment]
I have the same problem with Alpine Linux 3.9 (Docker image alpine:3.9)

**Comment by slivingston** [comment]
@DimShadoWWW I encountered a similar error. I suspect it does not originate in rabbitmq-c but rather how rabbitmq-c [is built by librabbitmq](https://github.com/celery/librabbitmq/blob/6917f2789903da5cbc497fc77a56e1d639294697/Makefile#L19). Try to install `pkg-config` first, then `pip install librabbitmq`

**Comment by nr23** [comment]
I fixed this by installing `cmake`, `libtool` and `autoconf`. (found this [here](https://github.com/celery/librabbitmq/issues/118#issuecomment-471002901))

On debian/ubuntu: `apt-get install cmake libtool autoconf`

**Comment by Wrufesh** [comment]
Mine was fixed with:
On ubuntu 22.04: `apt-get install pkg-config cmake libtool autoconf`

**Comment by alanxz** [comment]
`AMQ_PLATFORM` is defined by the build system, and will be correctly defined when built using the build system. Only `cmake` is required to build rabbitmq-c. `libtool` and `autoconf` are not used to build modern versions of rabbitmq-c. `pkg-config` can be optionally used (though it is not required).
