### ISSUE TITLE
run example,just got 'opening TCP socket'

### ISSUE THREAD

**Issue by XiaXuehai** [alanxz/rabbitmq-c#547]
compiled correct.and then run the example:
`./examples/amqp_listen localhost 5672 amq.direct test`

just got 'opening TCP socket', something wrong?
![image](https://user-images.githubusercontent.com/11585321/50887344-e9cb2800-142d-11e9-8869-bfbcb38f0017.png)

**Comment by ClimbSong** [comment]
solved？I got this issue too

**Comment by dabrain34** [comment]
yes I git the same ? Is it a duplicate ?

**Comment by kai06046** [comment]
@XiaXuehai have you solved this issue? please give some advice, thanks.

**Comment by kai06046** [comment]
ok...for those who also face this issue, just need to start a RabbitMQ server first, can install it from https://www.rabbitmq.com, default port is 5672.
