### ISSUE TITLE
Missing symbols in shared lib

### ISSUE THREAD

**Issue by jayvdb** [alanxz/rabbitmq-c#551]
Hiya, this library is used by a python extension, but is built into the extension instead of using the shared library, because of some symbols being missing, such as `amqp_simple_wait_frame_on_channel`

See
https://github.com/celery/librabbitmq/issues/9

**Comment by alanxz** [comment]
`amqp_simple_wait_frame_on_channel` is not a public API, thus it is not exported from the shared library and may change breaking anything that depends on it.

If you really must use this API, using a statically linked library will get you around this restriction.
