### ISSUE TITLE
Compatibility with ActiveMQ

### ISSUE THREAD

**Issue by ineffective** [alanxz/rabbitmq-c#552]
Is rabbitmq-c compatible with ActiveMQ AMQP implementation? Has anyone tested it? I cross-compile on Debian amd64 to armhf so it is possible that errors stem from some elusive errors and I'd like to confirm that it is indeed possible or not to connect to ActiveMQ.
I tried to connect to default amqp port 5762 (without SSL) using "amqp_producer". First try ended with:
`Logging in: unexpected method received`
After that I removed "amqp_login()" call from amqp_producer, recompiled, uploaded file and got:
`Opening channel: invalid AMQP data`
I suppose I could remove even more code, but I'm afraid I'll be left without any :)

**Comment by alanxz** [comment]
rabbitmq-c is not compatible with ActiveMQ.

**Comment by ineffective** [comment]
Thanks, that's what I feard. Could you please elaborate on why is that? Is it different protocol or different version or simply there is no real standard and implementations differ wildly?

**Comment by coterobarros** [comment]
It's a pitty that nowhere in the repo a reference to the supported version of AMQP can be found. I found the library very easy to use and helpful, but I've lost some time trying to connect to ActiveMQ, until I realized the library is for AMQP 0.9 only and ActiveMQ supports only 1.0.
