### ISSUE TITLE
Compiling in 32bits

### ISSUE THREAD

**Issue by rcanete2018** [alanxz/rabbitmq-c#558]
HI Can I compile the library in 32 bits?.

**Comment by alanxz** [comment]
Yes, rabbitmq-c can be compiled in 32-bit mode.

If your compiler does not produce 32-bit executables by default you will need to pass in the flag that enables this for your compiler to cmake.  For gcc or clang you would need to add `-DCMAKE_C_FLAGS="-m32"` when invoking CMake.
