### ISSUE TITLE
The delete function AMQP::~AMQP() call twice the function amqp_channel_close with channel number 1

### ISSUE THREAD

**Issue by nicolas-cadio** [alanxz/rabbitmq-c#568]
Hello,

When I delete my object AMQP, the server print this error: 
Error on AMQP connection <0.13378.0> (127.0.0.1:36354 -> 127.0.0.1:5672 - GATEWAY, vhost: 'AgvManager', user: 'ba_gateway', state: running), channel 1:
operation channel.close caused a connection exception channel_error: "expected 'channel.open'"

The delete function call twice the function amqp_channel_close with channel number 1:
- the first time in the loop for :
for (i=channels.begin(); i!=channels.end(); i++) {
			delete *i;  <== this one calls the delete AMQPBase => AMQPBase::closeChannel()
		}
 - the second time in the if  :
if (cnn != NULL) {
		amqp_channel_close(cnn, 1, AMQP_REPLY_SUCCESS);

is it neccary to call mqp_channel_close(cnn, 1, AMQP_REPLY_SUCCESS); ?

Thanks

**Comment by alanxz** [comment]
If you're tearing down the whole connection, you do not need to call `amqp_channel_close` on any channel.  Calling `amqp_channel_close` on an already closed channel will cause a connection exception, which destroys the whole connection.

**Comment by nicolas-cadio** [comment]
I don't call `ampq_channel_close`.
This is the destructor of the object `AMQP::~AMQP()` which call twice `ampq_channel_close`.

The source : 
```
AMQP::~AMQP() {
	if (channels.size()) {
		vector<AMQPBase*>::iterator i;
		for (i=channels.begin(); i!=channels.end(); i++) {
			delete *i;
		}
	}

	if (cnn != NULL) {
		amqp_channel_close(cnn, 1, AMQP_REPLY_SUCCESS);
		amqp_connection_close(cnn, AMQP_REPLY_SUCCESS);
		amqp_destroy_connection(cnn);
	}
};
```

The `delete *i` call the destructor of the object `AMQPBase::~AMQPBase()`
```
AMQPBase::~AMQPBase() {
	this->closeChannel();
}
```
And
```
void AMQPBase::closeChannel() {
	if (opened)
		amqp_channel_close(*cnn, channelNum, AMQP_REPLY_SUCCESS);
}
```

So when I call the destructor `AMQP::~AMQP()`, there is a first call to `amqp_channel_close` (with the destructor `AMQPBase::~AMQPBase()` and a second call to `amqp_channel_close` (`amqp_channel_close(cnn, 1, AMQP_REPLY_SUCCESS);`)

The first `amqp_channel_close` succeed but the second (`amqp_channel_close(cnn, 1, AMQP_REPLY_SUCCESS);`) fail because there is no check if the channel 1 is opened.

Regards
Nicolas
