### ISSUE TITLE
While printing "(char*)envelope.message.body.bytes", extra headers are added. How to remove them?

### ISSUE THREAD

**Issue by jadhavshital** [alanxz/rabbitmq-c#569]
Hi,
I want to write and read data using rabbitmq as broker. I did it but while fetching message from amqp_consume_message(conn, &envelope, NULL, 0), envelope.message.body.bytes are adding extra characters to it.

### Writer :- 
![writer](https://user-images.githubusercontent.com/17235485/60336849-19abbf00-99bf-11e9-8697-0cd0ec6596ff.PNG)

### Reader :- 
![reader](https://user-images.githubusercontent.com/17235485/60336858-24665400-99bf-11e9-8afe-029924e36c12.PNG)

### Writer :- 
`message_body = "Hello";`
`amqp_basic_publish(conn, 1, amqp_cstring_bytes("amq.direct"),
			amqp_cstring_bytes(queue_name), 0, 0, NULL,
			amqp_cstring_bytes(message_body));`

### Reader :- 
`amqp_rpc_reply_t ret;`
`amqp_envelope_t envelope;`

`amqp_maybe_release_buffers(conn);`
`ret = amqp_consume_message(conn, &envelope, NULL, 0);`

`cout << "Message body : "<<(char*)envelope.message.body.bytes << endl;`
`cout << "Message len : " << envelope.message.body.len << endl;`

### Required Output in reader :- 
```message13, Hi
message5
message14
message4
message5
message18
message10
message2
"hello":"1"
message22
message9
message11
message9
message3
message1
```

Suggest some method to get result as shown in required output.

**Comment by TreHack** [comment]
the same problem, but when I remove the `amqp_maybe_release_buffers`, it becomes ok.

**Comment by alanxz** [comment]
`amqp_cstring_bytes` does not include the trailing `\0` when creating the message body the writer, thus `message.body.bytes` in the output does not include the `\0` at the end of the string, thus the code is reading past the end of the buffer. You need to use `message.body.len` to determine where the end of the string is.

    std::string my_body = std::string(message.body.bytes, message.body.len);

Will correctly construct a `std::string` from the message.body.
