### ISSUE TITLE
Provide CMake targets for find_package() in vcpkg

### ISSUE THREAD

**Issue by wardj96** [alanxz/rabbitmq-c#572]
Hello there,

I am looking to include rabbitmq-c through vcpkg. Most vcpkg packages offer cmake targets to link the package library through the find_package() function. 

Protobuf, for example, brings these prompts after installing:

![image](https://user-images.githubusercontent.com/10851691/63534470-453db800-c4dd-11e9-9ad0-d3ff94c18fa5.png)

Something similar will make rabbitmq-c easier to use and more standard in the windows community and I was wondering how much effort it may be to implement these changes.

Thanks,
-Joe

**Comment by alanxz** [comment]
This is fixed by #611
