### ISSUE TITLE
amqp_channel_flow memory leak

### ISSUE THREAD

**Issue by xingyun86** [alanxz/rabbitmq-c#573]
My code is this:
bool check_state()
{
	bool state = false;
	amqp_channel_flow_ok_t * flow = amqp_channel_flow(conn, channel, true);
	state = (flow && flow->active == true);
	return state;
}

if(check_state())
{
  reconnect to mq.    
}

**Comment by alanxz** [comment]
You need to periodically call `amqp_maybe_release_buffers` after you're done with your `flow` object.
