### ISSUE TITLE
Bytes Receive and byte len is not matching.

### ISSUE THREAD

**Issue by bipindas2019** [alanxz/rabbitmq-c#574]
Hi ,

i am using amqp_consume_message() function to consume message. some times , the actual length of envelope.message.body.bytes and envelope.message.body.len  is not matching.
Some extrabytes are coming at end of receive message .  This issue is not always , some times it is coming.  there is no issue from producer side.

**Comment by anthonyclark-as** [comment]
Can you include the body of your message here? I'm curious if there is some multi-byte characters being sent. In which case `bytes != len`. If you're sending binary or ascii (and ensuring the message property is set, then this could be a bug.

**Comment by TreHack** [comment]
the same problem

**Comment by alanxz** [comment]
`envelope.message.body.bytes` is not necessarily a null-terminated string. Be sure to use the `envelope.message.body.len` to determine the correct number of bytes to read.

Its unlikely that `amqp_maybe_release_buffers` or `amqp_destroy_envelope` will result in correct behavior, both of these may release memory, using memory owned by after this will result in undefined behavior.

**Comment by bipindas2019** [comment]
> Can you include the body of your message here? I'm curious if there is some multi-byte characters being sent. In which case `bytes != len`. If you're sending binary or ascii (and ensuring the message property is set) then this could be a bug.

I am sending json message with text format.

**Comment by bipindas2019** [comment]
> `envelope.message.body.bytes` is not necessarily a null-terminated string. Be sure to use the `envelope.message.body.len` to determine the correct number of bytes to read.
> 
> Its unlikely that `amqp_maybe_release_buffers` or `amqp_destroy_envelope` will result in correct behavior, both of these may release memory, using memory owned by after this will result in undefined behavior.

Consumer should receive the exact bytes what producer send.  if producer terminate the msg with null terminate , consumer should receive it.
