### ISSUE TITLE
"a socket occurred error" help me~

### ISSUE THREAD

**Issue by tjkim0706** [alanxz/rabbitmq-c#577]
hi~.

Even with heartbeats enabled on the client, I get "a socket occurred error".
After using the heartbeat, the consumer does not occur and only the publisher generates a "a socket occurred error".

I configured the client using "SimpleAmqpClinet (c ++)" and communicating to rabbitmq server.
The error details are as follows.

-rabbitmq server log == ... authentication_failure_close ...
-SimpleAmqpClient (c ++) client log == a socket occurred error

I want to know what this error means and how to fix it.

Have a nice day.

**Comment by alanxz** [comment]
"authentication_failure_close" usually means that the wrong username/password is provided.

**Comment by tjkim0706** [comment]
> "authentication_failure_close" usually means that the wrong username/password is provided.

hi~

ID / password login via vhost works fine.
But when I do "publish" after login, the session is disconnected.
Only "publisher".

**Comment by alanxz** [comment]
Check the broker logs. 

Disconnects usually mean that the client has done something that is a protocol-level mistake (e.g., trying to use a channel that isn't open), thus a connection-exception occurs and the broker closes the connection.
