### ISSUE TITLE
Is it possible to perform a user create or credential pattern change with this library?

### ISSUE THREAD

**Issue by Joel-Mckay** [alanxz/rabbitmq-c#580]
I did not want to setup an custom application specific rabbitmq-auth back-end, but rather encapsulate the named-queue specific credentials imported from a mongo database into the AMQP server.

Very nice library, and I do understand there are probably some advantages of leaving administrative functions out of this part of the API.

(I read through the examples already, and assume this is not currently possible...)

Cheers,
J

**Comment by alanxz** [comment]
No.

This library only implements the AMQP protocol, which do not include user-management functions.
