### ISSUE TITLE
corrupt librabbitmq.pc

### ISSUE THREAD

**Issue by talih0** [alanxz/rabbitmq-c#599]
At the moment, the generated librabbitmq.pc file has an entry:

Libs.private: rt;-pthread
I believe it's supposed to be Libs.private: -lrt -lpthread

The redundant ";" will cause a compilation issue if the Libs.private flag is used.
This issue also exists on the ubuntu 16.04 packages. 
Are you able to fix and backport the changes?

FYI, I'm trying to add your AMQP implementation into FFmpeg which is using pkg-config. At the moment I cannot compile without manually changing your package config file.

**Comment by alanxz** [comment]
I can fix it in this repository at HEAD.  I do not maintain older versions of rabbimq-c, nor do I maintain any of the packages included as a part of a distribution, thus I cannot help there.

**Comment by alanxz** [comment]
I'm also curious what FFmpeg needs with an pubsub client library?

**Comment by talih0** [comment]
> I'm also curious what FFmpeg needs with an pubsub client library?

Usually, if you want to stream video to multiple clients you'd have to use a separate server like Nginx. FFmpeg is just a client that sends data to the server (An alternative is to use multicast)
Here, the idea is that you could use RabbitMQ to distribute the video instead.

By the way, you can already use a brokerless pub-sub via ZeroMQ on FFmpeg:
https://github.com/FFmpeg/FFmpeg/commit/ef43a4d6b38de941dd2ede0711d4fd5d811127ed

**Comment by talih0** [comment]
> I can fix it in this repository at HEAD. I do not maintain older versions of rabbimq-c, nor do I maintain any of the packages included as a part of a distribution, thus I cannot help there.

ok, thanks
