### ISSUE TITLE
Implementing Heartbeat functionality

### ISSUE THREAD

**Issue by shreyagarg011** [alanxz/rabbitmq-c#608]
Is there any method to implement heartbeat functionality using this library in C++?
I am using rabbitmq-c-0.10.0 on Windows10 in Visual Studio 2019 .
Please help.
Thanks

**Comment by alanxz** [comment]
rabbitmq-c is a C API. It can be used from C++. https://github.com/alanxz/SimpleAmqpClient does provide a convenient wrapper, though it does not currently support heartbeats.
