### ISSUE TITLE
channel left open after using it in Declare Passive when queue were gone, despite calling channel.close()

### ISSUE THREAD

**Issue by aaa091214** [alanxz/rabbitmq-c#616]
using Declare Passive to check if queue still exists (using a different channel, ID 3), 

amqp_channel_open(conn, 3);
amqp_queue_declare(conn, 3, queue_name, 1, 0,...);
amqp_channel_close(conn, 3, AMQP_REPLY_SUCCESS);

however, for cases when queue was gone, channel 3 was left open possible due to the exception seen in rabbitmq.log:

channel 3: operation queue.declare caused a channel exception not_found: no queue ‘clusterd.any’ in vhost ‘/’

list_channels also indicated there is channel 3 there in the system:
rabbitmqctl list_channels number 
...
3 

What do we need to do on client side in addition to ampq_channel_close() to have server to close the channel properly?

**Comment by aaa091214** [comment]
the solution seems to be client side needs to send channel.close-ok()? how do i do that in my context? and 
before ampq_channel_close() or after? Thanks!

**Comment by alanxz** [comment]
When `amqp_queue_declare` succeeds (no channel exception), then calling `amqp_channel_close` should close the channel correctly.

When `amqp_queue_declare` fails (channel exception occurs), you need to send an `channel.close_ok`:

    amqp_channel_close_ok_t close_ok;
    amqp_method_send(conn, 3, AMQP_CHANNEL_CLOSE_OK, &close_ok);

**Comment by aaa091214** [comment]
i see thanks so much!

**Comment by alanxz** [comment]
@aaa091214 correct.
