### ISSUE TITLE
follow-up on the #616: close channel if there's exception

### ISSUE THREAD

**Issue by aaa091214** [alanxz/rabbitmq-c#617]
sorry, have to follow up on this, checking the API documentation, saw there are different types of reply
AMQP_RESPONSE_NORMAL
AMQP_RESPONSE_SERVER_EXCEPTION and 
AMQP_RESPONSE_LIBRARY_EXCEPTION

not clear what to call for AMQP_RESPONSE_LIBRARY_EXCEPTION, 

if r.reply_type == AMQP_RESPONSE_NORMAL:
       // call channel close
        amqp_channel_close(conn, channel_id);
else:
       //call send_method
       amqp_channel_close_ok_t close_ok;
        amqp_send_method(conn_, PHANTOM_RABBIT_CHECK_CHANNEL, AMQP_CHANNEL_CLOSE_OK_METHOD, &close_ok);

**Comment by alanxz** [comment]
If `AMQP_RESPONSE_LIBRARY_EXCEPTION` is returned, you'll want to examine the [`library_error`](https://github.com/alanxz/rabbitmq-c/blob/c5cf965ed6d0233468fdea69e8a314f6d46b52c8/librabbitmq/amqp.h#L666-L668).  The value is one of the [`amqp_status_enum`](https://github.com/alanxz/rabbitmq-c/blob/c5cf965ed6d0233468fdea69e8a314f6d46b52c8/librabbitmq/amqp.h#L705-L774).  Usually this means that the connection is dead or in a bad state, your best bet is to destroy the whole connection and start again.
