### ISSUE TITLE
Bug when handling the server parameter in common.c

### ISSUE THREAD

**Issue by tinodj** [alanxz/rabbitmq-c#621]
I believe there is buggy behaviour in [common.c](https://github.com/alanxz/rabbitmq-c/blob/master/tools/common.c#L219) on line 219 - 'else' is missing on this if. If there is no colon in the servername (which is deprecated) then the host/servername is not properly set from parameters. 

You can see the original bug-report here: https://bugs.launchpad.net/ubuntu/+source/librabbitmq/+bug/1888313

**Comment by alanxz** [comment]
@tinodj should be fixed in the master branch, thanks for reporting it.

**Comment by tinodj** [comment]
Hi @alanxz - the fix in #622 is not complete I believe. The host is the one that was not set and was falling back to localhost. So, in the else, not only the port, but the host should be specified as wel.

**Comment by alanxz** [comment]
Hmm ok
