### ISSUE TITLE
amqp_consume does not respect the consumer channels if multiple are applied.

### ISSUE THREAD

**Issue by troglas** [alanxz/rabbitmq-c#624]
Hello Rabbitmq-c Team,
In one thread we we can have 2 channels and each of them can setup it's own queue consumer like this:
Channel 1 -> consumes Queue1
Channel 2 -> consumer Queue2

The amqp_consume_message does not have channel identifier passed so it reacts on message either from Queue1 or Queue2. 

As the channel is used to setup a consumer, and also a consumer tag links the channel and a queue together and a consumer is removed when the channel that created a consumer is removed, shouldn't the amqp_consume_message be given a Channel Id and return messages realated to the channel created consumer tag only ?

Best regards,
Kamil Górka

**Comment by alanxz** [comment]
@troglas your analysis of the current API is correct. The scope of `amqp_consume_message` is global to the connection, it does not allow you to consume from only a single channel or consumer*.  If you would like to do this, your best bet is to use `amqp_simple_wait_frame` to wait for a `basic.delivery` method to be delivered on the channel you care to wait for. You will need to store frames from other channels while processing the channel you desire. 

*A possibility of unbounded messages accumulating from another channel while waiting for a message on the desired channel is the reason that `amqp_consume_message` does not allow you to consume from a single channel or consumer. If you want to separate out processing of different consumers, your best bet is to use `amqp_consume_message`, then add an additional layer on top of this dispatch the message to the appropriate part of your code based on the consumer.
