### ISSUE TITLE
there's a bug in your generated pkg-config.pc file

### ISSUE THREAD

**Issue by teamblubee** [alanxz/rabbitmq-c#642]
After building your project from source

this 
```shell
Name: rabbitmq-c
Description: An AMQP 0-9-1 client library
Version: 0.10.0
URL: https://github.com/alanxz/rabbitmq-c
Requires.private: openssl
Libs: -L${libdir} -lrabbitmq
Libs.private: -t -pthread
CFlags: -I${includedir}
```

that's what the .pc file should look like but your output has this error:

```shell
Libs.private:\rt;-pthread
```

this obviously doesn't work and causes the build to fail.

Please take a look.

**Comment by alanxz** [comment]
This was previously reported in #599, and has subsequently been fixed.  The fix is in v0.11.0 and newer, please update to get this fix.
