### ISSUE TITLE
Unused SSL function? Might be needed to establish a full certificate chain via OpenSSL.

### ISSUE THREAD

**Issue by Kingcitaldo125** [alanxz/rabbitmq-c#655]
# The Issue
The [amqp_ssl_socket_set_cert](https://github.com/alanxz/rabbitmq-c/blob/219efb1179d9755b243adf69519a1344433bd964/librabbitmq/amqp_openssl.c#L487) function appears to be unused. Normally, I would not inform the developer(s) of just redundant code but this would be an issue when someone with a CA certificate(PEM), and a second certificate in a certificate chain(Client Certificate - TLS - PEM format), tries to establish a SSL using more than one `.crt` or `.pem` along with a private key.

The use case that I'm running into is fairly simple:
1. Load the CA certificate(`.crt`)
2. Load the second certificate in the cert chain(also `.crt`)
3. Finish off establishing the session by providing the private key(`.key`)

It appears that I can only use the following functions to establish the SSL:
[Set the CA cert](https://github.com/alanxz/rabbitmq-c/blob/master/examples/amqp_ssl_connect.c#L105)
[Set the private key](https://github.com/alanxz/rabbitmq-c/blob/master/examples/amqp_ssl_connect.c#L121)
[Login](https://github.com/alanxz/rabbitmq-c/blob/master/examples/amqp_ssl_connect.c#L129)

# Questions
The questions are:
How do I establish a SSL with RabbitMQ-C using the functions provided if I have 3 files(CA cert, TLS cert(client cert) and private key)?
Is this unused `amqp_ssl_socket_set_cert` an issue, or just basic code redundancy? If is is an issue, how do I establish the SSL in my use case?
Is a `amqp_login` actually required for SSL?

# Examples

Since I can't find a good C/C++ example, I'll try to illustrate using a Python(Pika client) example of what I'm seeking:

``` Python
import logging
import pika
import ssl

logging.basicConfig(level=logging.INFO)
context = ssl.create_default_context(
    cafile="PIKA_DIR/testdata/certs/ca_certificate.pem")
context.load_cert_chain("PIKA_DIR/testdata/certs/client_certificate.pem",
                        "PIKA_DIR/testdata/certs/client_key.pem")
ssl_options = pika.SSLOptions(context, "localhost")
conn_params = pika.ConnectionParameters(port=5671,
                                        ssl_options=ssl_options)

with pika.BlockingConnection(conn_params) as conn:
    ch = conn.channel()
    ch.queue_declare("foobar")
    ch.basic_publish("", "foobar", "Hello, world!")
    print(ch.basic_get("foobar"))
```

Thanks ahead of time,

PMA

**Comment by Kingcitaldo125** [comment]
Apologies ahead of time if this is actually a non-issue and I'm simply not establishing the SSL in the correct manner.
I'm new to working with server/client certificates, and SSL/TLS, in a pragmatic sense.
If this is a non-issue, suggestions on how to fulfill my current use case would be happily obliged.

**Comment by Kingcitaldo125** [comment]
While this thread is still open, I'm wondering: Do I have to call `amqp_login()` when using an SSL based socket?
I'm hoping that I can simply authenticate using the certs in the cert chain without having to login, which fits my current use case.

**Comment by alanxz** [comment]
@Kingcitaldo125 `amqp_login` could just as easily be named "perform handshake".  So yes you will need to use this when connecting to the broker.  You may be able to use an alternative SASL mechanism to authenticate against the broker. The two that are supported by rabbitmq-c are [`PLAIN` and `EXTERNAL`](https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp.h#L676-L682). Where plain is username + password, and external is some identity plus an external method like the broker examining the SSL cert (you'll need to refer to the rabbitmq broker documentation here).

**Comment by Kingcitaldo125** [comment]
Thanks a bunch for the response here. It seems that, since we're wanting to use SSL/TLS exclusively, I can specify `EXTERNAL` like you mentioned with a default username/blank passwd to authenticate against the broker. We have a mildly complicated(to me lol) server/client certificate mechanism setup right now, and we wanted to forgo having to manage N username/password combos and authenticate purely using the certs in our cert chain.... Your response was a good deal of help to me, and the rest of our team, so thank you!

**Comment by Kingcitaldo125** [comment]
The unused SSL function does not appear to be correlated to the issue described here, so that is reason enough to close this issue IMO.
It is possible to load up two certificates( CA and client - in `PEM` format ) and the private key to establish the context for the chain of trust when going to establish a SSL/TLS layer using this client.

The two function calls that handle this are:
- `amqp_ssl_socket_set_cacert()`
- `amqp_ssl_socket_set_key()`

Pass in the CA Certificate location to the first one, along with the socket pointer.
Pass in the location of the client certificate and the private key, in that order, to the second function along with the socket pointer.

When going to login to the broker, using `amqp_login()`, no username/password should be needed since the certificates and private key are used exclusively to authenticate.
`AMQP_SASL_METHOD_EXTERNAL` should be passed in instead of `AMQP_SASL_METHOD_PLAIN` if you're trying to authenticate with the broker using X.509( peer certificate verification - [Ref](https://www.rabbitmq.com/access-control.html#mechanisms) ).

ex.

```
amqp_login(conn, "/", 0, 131072, 0, AMQP_SASL_METHOD_EXTERNAL)
```

Opening the socket is the same, it's just being done using a socket that was instantiated using the `amqp_ssl_socket_new()` function.
I hope that helps anyone who ran into the same conundrum that I did.

**Comment by Kingcitaldo125** [comment]
It is worth mentioning that the [amqp_ssl_connect](https://github.com/alanxz/rabbitmq-c/blob/master/examples/amqp_ssl_connect.c) example does this differently. This threw me for a huge loop when I was trying to follow that example to do what I needed to do...
