### ISSUE TITLE
Missing amqp.c source file

### ISSUE THREAD

**Issue by Seetha102** [alanxz/rabbitmq-c#656]
Hi,

 While building using cmake of amqp_listen.c i get several methods not referenced .Following are some of the methods unreferenced
amqp_channel_open
amqp_new _connection....

All these methods

**Comment by alanxz** [comment]
Make sure that you link against the rabbitmq-c library when building it.

This usually means adding a flag to your compiler invocation that includes the library (see the manual for your compiler).
