### ISSUE TITLE
Anyone knows the API for getting the number of messages on the queue??

### ISSUE THREAD

**Issue by toshhy** [alanxz/rabbitmq-c#658]

**Comment by alanxz** [comment]
Calling [`amqp_queue_declare`](https://github.com/alanxz/rabbitmq-c/blob/4da42f0ffb832bffe75ada174caad47412d2a0a4/librabbitmq/amqp_framing.h#L969-L986) then the number of messages in the queue will be in the `message_count` member of the returned [`amqp_queue_declare_ok_t`](https://github.com/alanxz/rabbitmq-c/blob/4da42f0ffb832bffe75ada174caad47412d2a0a4/librabbitmq/amqp_framing.h#L470-L474).
