### ISSUE TITLE
Missing include

### ISSUE THREAD

**Issue by mgaeckler1964** [alanxz/rabbitmq-c#692]
Hi,

recently I've downloaded master and tried to comile. In master/include/rabbitmq-c/amqp.h there is an include of rabbitmq-c/export.h that is not part of the repository. Did you forget to include this file in your commit?

BR Martin

**Comment by alanxz** [comment]
The export.h is [generated by the CMake build-system](https://github.com/alanxz/rabbitmq-c/blob/883ddc06267e39b24fd5ac504a3485de685aef09/librabbitmq/CMakeLists.txt#L149), and should be installed as a [part of the `install` target](https://github.com/alanxz/rabbitmq-c/blob/883ddc06267e39b24fd5ac504a3485de685aef09/librabbitmq/CMakeLists.txt#L168).

**Comment by mgaeckler1964** [comment]
Thanks. My problem is that I do ot have CMake installed on my built system. Is there a chance to create the file without CMake or do I have to install CMake?

**Comment by alanxz** [comment]
No, the only currently supported build-system is CMake.  If you need the export.h on a system that doesn't have cmake, your best bet is to cross-compile it on a system that does have cmake, and copy it over.
