### ISSUE TITLE
no examples/amqp_listen.o file

### ISSUE THREAD

**Issue by cherryMJY** [alanxz/rabbitmq-c#694]

**Comment by cherryMJY** [comment]
just in build file   cmake ..  and cmake --build .      but, i do not find  amqp_listen.o file. only find amqp_listen.c file.

**Comment by cherryMJY** [comment]
or  where is the  amqp_listen.o file ?

**Comment by cherryMJY** [comment]
no  build/examples file.

**Comment by alanxz** [comment]
Examples are not built by default. You must specify `-DBUILD_EXAMPLES=ON` to build the example code.

Once you do that: examples/amqp_listen.o will be in the binary or build directory
