### ISSUE TITLE
List of error codes?

### ISSUE THREAD

**Issue by ninomllr** [alanxz/rabbitmq-c#701]
I am using the pg_amqp library https://github.com/omniti-labs/pg_amqp because I want to publish to RabbitMQ from Postgres, but I can't connect to my CloudAMQP instance. My C is extremely rusty, so I am having trouble in getting the right information from the code. Basically I get the error `2021-08-02 13:28:26.230 UTC [32] WARNING: amqp[url:port] login failed on broker 1` in their library, which comes from the following code part:

```
s_reply = amqp_login(bs->conn, vhost, 0, 131072,
                     0, AMQP_SASL_METHOD_PLAIN,
                     user, pass);
if (s_reply.reply_type != AMQP_RESPONSE_NORMAL)
{
  elog(WARNING, "amqp[%s] login failed on broker %d", host_copy, broker_id);
  goto busted;
}
```

s_reply.reply_type is `AMQP_RESPONSE_LIBRARY_EXCEPTION` and s_reply.library_errno = 1. Is there a list of what those error codes mean and how I can find out what really goes wrong here? Or is there a way to get the response from RabbitMQ to find out what goes wrong?

**Comment by alanxz** [comment]
You can compare the value to the [`amqp_status_enum`](https://github.com/alanxz/rabbitmq-c/blob/027a626d8c82e70557a33cfd64d3b41dc6faa094/include/rabbitmq-c/amqp.h#L604-L674), or use the [`amqp_error_string2`](https://github.com/alanxz/rabbitmq-c/blob/027a626d8c82e70557a33cfd64d3b41dc6faa094/include/rabbitmq-c/amqp.h#L1967-L1979) API to turn a library error into a human readable error-string.

It does appear to be a bit weird that you're getting a value of `1` for a library error-code, enums are all negative numbers.

There may also be some additional information about issues with connection failure in the RabbitMQ broker log.

**Comment by alanxz** [comment]
Given no additional response, I assume you're satisfied with the above answer, please re-open if this is not the case.
