### ISSUE TITLE
Is rabbitmq-c can work with Azure Service Bus

### ISSUE THREAD

**Issue by fzacharie** [alanxz/rabbitmq-c#704]
Hi Alanxz, 

First of all, thank you very much for your library, I'm using it in Delphi with RabitMQ and it's work very well!
Now I have to move my project to "Azure Service Bus" and I was wondering to know if it's possible doing it with your library ?

I'm worming with Delphi and I'm using https://github.com/HeZiHang/Delphi-RabbitMQ header file conversion from you c headers to Delphi header...

Thank you!
Best regard!
François

**Comment by alanxz** [comment]
[Azure Service Bus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview) uses AMQP 1.0, while this library implements AMQP v0.9.1.

So unfortunately rabbitmq-c will not work with Azure Service Bus.

**Comment by fzacharie** [comment]
ok, thank you Alanxz!
Is it in your plan to implement AMQP 1.0 in the futur in you librairy ?

Thank you for your good work!!!
Francois

**Comment by alanxz** [comment]
Despite the name being very similar: AMQP v1.0 and v0.9.1 are very different protocols (and the RabbitMQ broker isn't planning on switching to v1.0). So currently I don't plan on implementing AMQP v1.0 in rabbitmq-c.

**Comment by fzacharie** [comment]
ha! ok,

I will do some research to try to find a library implementing AMQP 1.0 for Delphi (or C++).
If never you know one, please let me know.

have a nice day!
Thank!
Francois

**Comment by alanxz** [comment]
https://github.com/azure/azure-uamqp-c/ and https://qpid.apache.org/proton/index.html are C/C++ libraries that implement AMQP 1.0
