### ISSUE TITLE
Can't compile examples folder

### ISSUE THREAD

**Issue by goncalo-almeida-mc** [alanxz/rabbitmq-c#705]
I followed all the steps on ReadMe but trying to compile the examples I get a linking error:

$ make

[  9%] Built target examples-common
[ 13%] Linking C executable amqp_listenq
/usr/bin/ld: cannot find -lrabbitmq::rabbitmq
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/amqp_listenq.dir/build.make:88: amqp_listenq] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/amqp_listenq.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

Any hint on how I should proceed?

**Comment by goncalo-almeida-mc** [comment]
I found out that -lrabbitmq relates to librabbitmq.so but this is the output i get for `ls -l /usr/local/lib/librabbitmq*`

-rw-r--r-- 1 root root 170832 ago 19 09:25 /usr/local/lib/librabbitmq.a
lrwxrwxrwx 1 root root     16 ago 19 13:01 /usr/local/lib/librabbitmq.so -> librabbitmq.so.4
-rw-r--r-- 1 root root 109504 ago 19 09:25 /usr/local/lib/librabbitmq.so.0.12.0
lrwxrwxrwx 1 root root     21 ago 19 13:01 /usr/local/lib/librabbitmq.so.4 -> librabbitmq.so.0.12.0

**Comment by alanxz** [comment]
What version of CMake are you using?

**Comment by goncalo-almeida-mc** [comment]
3.16.3

**Comment by alanxz** [comment]
There have been a number of recent changes to the way that libraries are specified inside the CMakeLists.txt, this might be related.

Could you try (temporarily) building with the most recent version of CMake?

Additionally could you tell me a bit more about your environment you're building in? Specifically which OS and version?

**Comment by goncalo-almeida-mc** [comment]
I'm using Linux 20.04.
I've updated CMake to 3.21, redone the steps and the output of `make` remains with the same error.

**Comment by goncalo-almeida-mc** [comment]
Update: I managed to finally compile it. 

The generated `link.txt` (path: `examples/CMakeFiles/<filename>.dir/link.txt`) for each file had `-lrabbitmq::rabbitmq` at the end.
When I tried to leave only `-lrabbitmq`, it worked.

Still don't know why it worked, maybe the problem was a misgeneration of those link.txt files?

**Comment by goncalo-almeida-mc** [comment]
Update: I managed to finally compile it. 

The generated `link.txt` (path: `examples/CMakeFiles/<filename>.dir/link.txt`) for each file had `-lrabbitmq::rabbitmq` at the end.
When I tried to leave only `-lrabbitmq`, it worked.

Still don't know why it worked, maybe the problem was a misgeneration of those link.txt files?

**Comment by aohanhongzhi** [comment]
![image](https://user-images.githubusercontent.com/37319319/202651431-ea90cc0c-20cb-43d9-8a0a-257f7a148530.png)

**Comment by migabc** [comment]
Hi,

I'm having the same issue:

`[smsc@CETPSVMM004 examples]$ mkdir build && cd build
[smsc@CETPSVMM004 build]$ cmake ..
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.27)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done (0.6s)
CMake Warning (dev) at CMakeLists.txt:13 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "examples-common" links to:

    rabbitmq::rabbitmq

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:16 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "amqp_sendstring" links to:

    rabbitmq::rabbitmq

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:19 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "amqp_rpc_sendstring_client" links to:

    rabbitmq::rabbitmq

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:22 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "amqp_exchange_declare" links to:

    rabbitmq::rabbitmq

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:25 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "amqp_listen" links to:

    rabbitmq::rabbitmq

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:28 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "amqp_producer" links to:

    rabbitmq::rabbitmq

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:31 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "amqp_connect_timeout" links to:

    rabbitmq::rabbitmq

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:34 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "amqp_consumer" links to:

    rabbitmq::rabbitmq

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:37 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "amqp_unbind" links to:

    rabbitmq::rabbitmq

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:40 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "amqp_bind" links to:

    rabbitmq::rabbitmq

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:43 (target_link_libraries):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "amqp_listenq" links to:

    rabbitmq::rabbitmq

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done (0.0s)
-- Build files have been written to: /home/smsc/RabbitMQ/rabbitmq-c-0.13.0/examples/build
[smsc@CETPSVMM004 build]$ 


[smsc@CETPSVMM004 build]$ ls -lFart
total 48
drwxrwxr-x  5 smsc smsc  4096 Oct  5 22:28 ../
-rw-rw-r--  1 smsc smsc 14676 Oct  5 22:28 CMakeCache.txt
-rw-rw-r--  1 smsc smsc 17978 Oct  5 22:28 Makefile
-rw-rw-r--  1 smsc smsc  1668 Oct  5 22:28 cmake_install.cmake
drwxrwxr-x 16 smsc smsc  4096 Oct  5 22:28 CMakeFiles/
drwxrwxr-x  3 smsc smsc    89 Oct  5 22:28 ./
[smsc@CETPSVMM004 build]$ 



[smsc@CETPSVMM004 build]$ cmake --build .
[  4%] Building C object CMakeFiles/examples-common.dir/utils.o
/home/smsc/RabbitMQ/rabbitmq-c-0.13.0/examples/utils.c:10:29: fatal error: rabbitmq-c/amqp.h: No such file or directory
 #include <rabbitmq-c/amqp.h>
                             ^
compilation terminated.
gmake[2]: *** [CMakeFiles/examples-common.dir/utils.o] Error 1
gmake[1]: *** [CMakeFiles/examples-common.dir/all] Error 2
gmake: *** [all] Error 2
[smsc@CETPSVMM004 build]$
`

Any help apreciated
