### ISSUE TITLE
0.12.0 - is there a plan to release?

### ISSUE THREAD

**Issue by inikulshin** [alanxz/rabbitmq-c#740]
Or 0.11.1? Is there any release policy?

We would like to use some **tagged** commit that supports both OpenSSL 3.0.0 (in 0.11.0) and TLS1.3 (exists only in master)...

**Comment by dagardner-nv** [comment]
Agreed, there are some cmake fixes that we would like to pick up, preferably from a version tag.

**Comment by alanxz** [comment]
v0.12.0 has been tagged and published.

**Comment by dagardner-nv** [comment]
Awesome, thank you!
