### ISSUE TITLE
How to compile RabbitMQ for SSL

### ISSUE THREAD

**Issue by ManjuMandya** [alanxz/rabbitmq-c#757]
Hi,
    I have v0.8.0 version RabbitMQ. I am able to compile and use library for "http". When i tried compiling for "https", compiler is throwing error. Could someone help me in resolving this issue
Details below:
1) Version : v0.8.0
2) Command issued for secured Rabbit MQ
  cmake -DCMAKE_TOOLCHAIN_FILE=Toolchain-eldk-ppc74xx.cmake -DENABLE_SSL_SUPPORT=True ..
3) Command for compilation:
     cmake --build .
I get below error:

[  1%] Building C object librabbitmq/CMakeFiles/rabbitmq.dir/amqp_openssl.c.o
In file included from /home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:32:
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl_hostname_validation.h:34:20: error: x509v3.h: No such file or directory
In file included from /home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:32:
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl_hostname_validation.h:57: warning: type defaults to 'int' in declaration of 'X509'
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl_hostname_validation.h:57: error: expected ';', ',' or ')' before '*' token
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:41:26: error: openssl/conf.h: No such file or directory
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:42:25: error: openssl/err.h: No such file or directory
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:43:25: error: openssl/ssl.h: No such file or directory
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:44:28: error: openssl/x509v3.h: No such file or directory
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:71: error: expected specifier-qualifier-list before 'SSL_CTX'
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c: In function 'amqp_ssl_socket_send':
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:83: error: 'struct amqp_ssl_socket_t' has no member named 'sockfd'
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:93: warning: implicit declaration of function 'ERR_clear_error'
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:94: error: 'struct amqp_ssl_socket_t' has no member named 'internal_error'
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:98: warning: implicit declaration of function 'SSL_write'
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:98: error: 'struct amqp_ssl_socket_t' has no member named 'ssl'
/home/manju/Projects/Pegasus/RabbitMQ/RabbitMQ/librabbitmq/amqp_openssl.c:100: error: 'struct amqp_ssl_socket_t' has no member named 'internal_error'
![RabbitMQ_Compilation](https://user-images.githubusercontent.com/75018500/219018769-fb2d7f24-a423-46a3-9854-0b2a69b3a283.jpg)

**Comment by alanxz** [comment]
It looks like you may not have the OpenSSL library headers installed on your system. I believe the `libssl-dev` package is what you will need to install (e.g., `sudo apt-get install libssl-dev`).

As an aside: v0.8.0 is a very old version of this library, I would recommend using the latest version of rabbitmq-c if possible.

**Comment by ManjuMandya** [comment]
I do have OpenSSL library installed in my system. I have also cross compiled Curl ( for https ) with OpenSSL on the same system.

**Comment by alanxz** [comment]
The issue is that the compiler cannot find the OpenSSL headers.  You may need to override what CMake finds using `-D OPENSSL_INCLUDE_DIR=...`. See: https://cmake.org/cmake/help/latest/module/FindOpenSSL.html
