### ISSUE TITLE
macOS dylib minor versions make no sense since 0.12.0

### ISSUE THREAD

**Issue by ryandesign** [alanxz/rabbitmq-c#758]
In 0.12.0 (6342f395024c9d595a9c29d429bf344aa3269423?) you changed the library versioning in a way that does not make sense on macOS.

0.11.0:

```
% otool -L /opt/local/lib/librabbitmq.dylib
/opt/local/lib/librabbitmq.dylib:
	/opt/local/lib/librabbitmq.4.dylib (compatibility version 4.0.0, current version 4.5.0)
	/opt/local/libexec/openssl3/lib/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/opt/local/libexec/openssl3/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

0.12.0:

```
% otool -L /opt/local/lib/librabbitmq.dylib
/opt/local/lib/librabbitmq.dylib:
	/opt/local/lib/librabbitmq.4.dylib (compatibility version 4.0.0, current version 0.12.0)
	/opt/local/libexec/openssl3/lib/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/opt/local/libexec/openssl3/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

A macOS dynamic library has a major version (which is part of the filename) and a minor version (which are properties within the library file). A library advertises its current minor version, and a possibly earlier minor version with which it is compatible.

In 0.11.0, your library's major version was 4, and you advertised that its minor version was 4.5.0 and that it was compatible with minor library versions back to 4.0.0. In other words, any program that was compiled with librabbitmq major 4 minor 4.0.0 or later will work fine with librabbitmq major 4 minor 4.5.0.

In 0.12.0, the major version is unchanged but you now advertise that your current minor version is 0.12.0, which is less than the previous minor version; library versions should never decrease like that. You also still claim that major 4 minor 0.12.0 is backward compatible with major 4 minor 4.0.0, which makes no sense since 4.0.0 is a larger number than 0.12.0.

**Comment by alanxz** [comment]
The change was intensional to better align the meanings of version and SOVERSION; which on Linux allows for this sort of flexibility.  What was not expected is that MacOS uses the VERSION in the way that it does, where this appears to make the version go backwards so that library selection doesn't work as expected.

As such I will adjust the next released version so that on MacOS the current-version > 4.5.0 (likely it'll be 4.14.0)
