### ISSUE TITLE
The repository has a broken commit

### ISSUE THREAD

**Issue by turbocat2001** [alanxz/rabbitmq-c#765]
An error occurs when trying to fork a project on Gitlab.

For Gitlab:
```log
Enumerating objects: 5915, done.
Counting objects: 100% (5915/5915), done.
Delta compression using up to 12 threads
Compressing objects: 100% (1871/1871), done.
Writing objects: 100% (5915/5915), 2.13 MiB | 32.59 MiB/s, done.
Total 5915 (delta 3957), reused 5915 (delta 3957), pack-reused 0
remote: error: object 3cb254d902a9b226bf95696af3a98839bb7797a4: badDate: invalid author/committer line - bad date
remote: fatal: fsck error in packed object
error: remote unpack failed: index-pack abnormal exit
```

Judging by the output for the gitlab, this is a broken date. Can you fix this somehow?

**Comment by alanxz** [comment]
Unfortunately it's infeasible to fix this as correcting the bad commit
involves rewriting the history <https://stackoverflow.com/q/59231306/786714>
for the whole repository. See this existing issue:
https://github.com/alanxz/rabbitmq-c/issues/372

-Alan

**Comment by turbocat2001** [comment]
Thanks for the answer. In this case, you can close this since such an issue already exists.
