### ISSUE TITLE
Publishes sometimes fail silently

### ISSUE THREAD

**Issue by Cazra** [alanxz/rabbitmq-c#766]
Sometimes when I publish a message using `amqp_basic_publish`, the connection fails silently and I don't receive the message on the queue at the other end of my application. Nothing went wrong with the receiving queue. I'm able to start a new connection, publish messages over my exchange and (usually) have them go through (unless the publisher's connection fails silently again).

Is there a way to confirm with this library for sure whether a published message has been successfully consumed or not?

**Comment by ostreamBaba** [comment]
the same issue.

**Comment by alanxz** [comment]
Yes - you will want to use [publisher confirms](https://www.rabbitmq.com/confirms.html#publisher-confirms) feature of RabbitMQ.

You can do this in rabbitmq-c by:

On the channel you want to publish messages on enable the publisher confirms feature:

[`amqp_confirm_select()`](https://github.com/alanxz/rabbitmq-c/blob/8889ef336d7af66fb4a0e3398db4c3701c33d3e1/include/rabbitmq-c/framing.h#L1144-L1146).

Then after calling `amqp_basic_publish`, use [`amqp_simple_wait_frame`](https://github.com/alanxz/rabbitmq-c/blob/8889ef336d7af66fb4a0e3398db4c3701c33d3e1/include/rabbitmq-c/amqp.h#L1382C15-L1383) to wait for a `basic.ack` method to be returned from the broker.
