### ISSUE TITLE
Man page "amqp-publish" -> "amqp-consume"

### ISSUE THREAD

**Issue by jppaulo06** [alanxz/rabbitmq-c#791]
https://github.com/alanxz/rabbitmq-c/blob/9a91cf59760471b49307535d839d38d6c9a08d66/tools/doc/amqp-consume.xml#L197C14-L197C14

**In amqp-consume man page, it is written:**

_Consume messages from an existing queue “myqueue”, and output the message bodies on
standard output via cat:
 `$ amqp-publish -q myqueue cat`_

I think the command line should change to:
 `$ amqp-consume -q myqueue cat`

**Comment by alanxz** [comment]
This does appear to be a bug, if you have time could you send me a PR updating the docs?
