### ISSUE TITLE
How to Check if RabbitMQ Server is Configured Before Binding Queues and Notifications?

### ISSUE THREAD

**Issue by kwitekrac** [alanxz/rabbitmq-c#799]
I am facing an issue in my system where the queues and notifications are configured by the server, and the client application, which uses rabbitmq-c, can be launched before the server is fully configured. To handle this scenario, I need to implement an algorithm that checks if the queue and notification exist before attempting to bind them. I have tried using the 'declare notification' and 'declare queue' operations with the passive flag in rabbitmq-c. However, on the second execution, it hangs the execution of the thread and returns an error, which I understand is not a bug but a feature according to this GitHub [issue](https://github.com/alanxz/rabbitmq-c/issues/409).

I'm wondering if there are any other options or workarounds within the rabbitmq-c library that would allow me to check if the RabbitMQ server is already configured before attempting to bind queues and notifications? Any insights or suggestions would be greatly appreciated.

**Comment by alanxz** [comment]
Declaration of queues, exchanges and bindings is idempotent, meaning the declaration has no effect if the object already exists.  A suggested design pattern is if your client depends on a object being available, you should declare it without checking for its existence first, the server will create any objects that don't exist and will have no effect for things that already do exist.

In terms of 'hanging execution' you're observing using when using the passive flag, its likely that the server has closed the connection, as your use has violated the AMQP protocol.  If you want to use the passive flag to check for a queues existance you'd need to do the following:

1. Call amqp_declare_queue with the passive flag set.
2. If the function returns a non-null result, it means the queue already exists, no further action is required.
3. If the function returns a null result, you must get the last reply using amqp_get_rpc_reply.
4.  If you get a channel.close error - that means that the queue does not exists, it also means that the server has closed the channel. Your code must then send a channel.close-ok method to the broker, then must open a new channel to continue using the connection. If you attempt to reuse the channel without re-opening, the server considers this a protocol error and will close the underlying tcp connection - which may make the library appear to hang (in this case there's a long-timeout before the connection closure is detected).
5. If you get a connection.close, the whole connection has been terminated, you'll need to create a new connection to continue.

This is [documented here](https://github.com/alanxz/rabbitmq-c/blob/a2d04a436a0cd53c7d441453455cdbab0831653d/include/rabbitmq-c/amqp.h#L1630C28-L1630C46)

**Comment by kwitekrac** [comment]
ok, it makes sense. Thank you for your explanation.
