### ISSUE TITLE
Hello, utils. c is missing two functions now_ Microseconds and microsleeps

### ISSUE THREAD

**Issue by predatorbigbear** [alanxz/rabbitmq-c#800]
Hello, utils. c is missing two functions now_ Microseconds and microsleeps

**Comment by alanxz** [comment]
I assume you're referring to the functions declared https://github.com/alanxz/rabbitmq-c/blob/master/examples/utils.h.

These are defined in 
* https://github.com/alanxz/rabbitmq-c/blob/master/examples/unix/platform_utils.c
* https://github.com/alanxz/rabbitmq-c/blob/master/examples/win32/platform_utils.c

Depending on which platform you're compiling for.  The CMake build system should pick the correct one depending on what platform you're compiling for.
