### ISSUE TITLE
Duplicate connection and channel

### ISSUE THREAD

**Issue by nickolajgrishuk** [alanxz/rabbitmq-c#804]
Hi, I'm using the latest version of the library.
The library is used in an embedded device, and there is a problem when an uncontrolled disconnection of the device from power occurs: in RabbitMQ itself the connection is not broken, and reapplying power creates a duplicate connection and channel

Please tell me a solution on how to interrupt the connection if it physically no longer exists, maybe there is some option that I blindly did not see?

**Comment by reunanen** [comment]
Have you tried enabling [heartbeat](https://github.com/alanxz/rabbitmq-c/blob/c3550e7accda82a55f7c142284de65f117b30977/include/rabbitmq-c/amqp.h#L1652-L1656)?

**Comment by nickolajgrishuk** [comment]
> tried enabling [heartbeat](https://github.com/alanxz/rabbitmq-c/blob/c3550e7accda82a55f7c142284de65f117b30977/include/rabbitmq-c/amqp.h#L1652-L1656)?

Thank you very much, I didn’t notice that it was 0 instead of 1, now it works correctly
