### ISSUE TITLE
OpenSsl v3.x fips mode question.

### ISSUE THREAD

**Issue by kirill-y** [alanxz/rabbitmq-c#813]
Is it possible to use the library with openssl 3.x in fips mode ?

I tryed it in strait forward manner, and got **SSL_R_LIBRARY_HAS_NO_CIPHERS** error from **got SSL_CTX_new()** call, called from **amqp_ssl_socket_new()**

**Comment by alanxz** [comment]
@kirill-y can you share your code?

**Comment by alanxz** [comment]
rabbitmq-c does nothing that would prevent OpenSSL 3.x from working in FIPS mode.  Without more detailed information about your case, its difficult for me to provide a better answer here.

**Comment by kirill-y** [comment]
Sorry for delay,

I'm wrapping your code, and it should be used by different components(services), so I cant rely on 
enabling FIPS mode via openssl environment variables, I should to control FIPS mode on "my" component level.
I tried to use nondefault openssl library context.

According to https://www.openssl.org/docs/manmaster/man7/fips_module.html -
section "Programmatically loading the FIPS module (nondefault library context)"

my initization code looks like:

```
OSSL_LIB_CTX *fips_libctx, *nonfips_libctx;
OSSL_PROVIDER *defctxnull = NULL;

fips_libctx = OSSL_LIB_CTX_new();
nonfips_libctx = OSSL_LIB_CTX_new();
if (fips_libctx == NULL || nonfips_libctx == NULL)
    goto err;

defctxnull = OSSL_PROVIDER_load(NULL, "null");

if (!OSSL_LIB_CTX_load_config(fips_libctx, "openssl-fips.cnf"))
    goto err;

if (!EVP_set_default_properties(fips_libctx, "fips=yes"))
    goto err;

return 0;

err:
OSSL_LIB_CTX_free(fips_libctx);
OSSL_LIB_CTX_free(nonfips_libctx);
OSSL_PROVIDER_unload(defctxnull);
return 1;

```
It create fips library context, and disables the default one.
At latest stage amqp_ssl_socket_new() is called and it failed
 with self->ctx = SSL_CTX_new(SSLv23_client_method()) call than uses disabled default libray context.
 
The openssl documetnation mentioned above, section "Using the FIPS module in SSL/TLS",
refers certain way to get SSL_CTX* in a fips mode.
