### ISSUE TITLE
Using Update_Secret method : COMMAND_INVALID - unimplemented method

### ISSUE THREAD

**Issue by lanisys** [alanxz/rabbitmq-c#815]
Hi,
I'm using rabbitmq-c client on AIX (i've compiled it), used along a rabbitmq server version 3.12.10
Connection, publishing and consuming message are working fine, but Update_Secret method is always going wrong : COMMAND_INVALID - unimplemented method

I've got this error on server's log :

2024-01-18 15:38:25.813748+00:00 [error] <0.24531.16> operation connection.update_secret caused a connection exception command_invalid: "unimplemented method" 

this is my code:

```
bool Amqp::MettreAJourLeJeton(const char * jeton)
{
    amqp_connection_update_secret(m_Connexion, m_Canal, amqp_cstring_bytes(jeton), amqp_cstring_bytes("expiration token"));
    return(amqp_get_rpc_reply(m_Connexion).reply_type == AMQP_RESPONSE_NORMAL);
}
```

Can you help me ? The same method called from .Net client is working fine (on the same server)
Thank's
Fred

**Comment by lanisys** [comment]
this is my code:

```
bool Amqp::MettreAJourLeJeton(const char * jeton)
{
    amqp_connection_update_secret(m_Connexion, m_Canal, amqp_cstring_bytes(jeton), amqp_cstring_bytes("expiration token"));
    return(amqp_get_rpc_reply(m_Connexion).reply_type == AMQP_RESPONSE_NORMAL);
}
```

**Comment by alanxz** [comment]
Try using channel 0 when calling amqp_connnection_update_secret

**Comment by lanisys** [comment]
Thanks for your quick return. I tested and It works on channel 0. thank you very much 👍
