### ISSUE TITLE
Can I use a proxy?

### ISSUE THREAD

**Issue by drum0103** [alanxz/rabbitmq-c#816]
We are currently working on a project using rabbitmq-c-0.11.0.

However, a situation arises where I need to use a proxy, 
and I want to reflect proxy information, 
but I don't know how.

Does rabbitmq-c-0.13.0 currently support proxy?
If so, how can I use it?
I couldn't find it in the current example. Of course, the same applies to Google searches.

I can reflect the proxy by reflecting the proxy in libcurl when calling curl through the rest API, 
but I want to know if there is a special function in amqp.

ask for help please.

**Comment by alanxz** [comment]
rabbitmq-c does not provide any APIs specific to connecting to a broker via a proxy, and I don't know of anyone who has tried to do this.

That said, there's nothing specific about the library that would prevent it from being used to connect to a broker behind a proxy. You will need some additional software to establish a TCP connection through the proxy, then use the [`amqp_tcp_socket_set_sockfd`](https://github.com/alanxz/rabbitmq-c/blob/7337e10105df20b393c5f8ef810c75a7c72eabcc/include/rabbitmq-c/tcp_socket.h#L43) to allow rabbitmq-c to connect to the broker.
