### ISSUE TITLE
RabbitMQ C installed but not detectable by the system (WSL Ubuntu-22.04)

### ISSUE THREAD

**Issue by GerRubio** [alanxz/rabbitmq-c#817]
Hello. I just have installed RabbitMQ C but the system does not detect it and because of this reason, my Dockerfile fails when it tries to install "amqp".

This is the error message I get:

```
57.09 checking for amqp using pkg-config... configure: error: librabbitmq not found
57.11 ERROR: `/tmp/pear/temp/amqp/configure --with-php-config=/usr/local/bin/php-config --with-librabbitmq-dir' failed
```

I'd appreciate any help.

Thanks.

**Comment by alanxz** [comment]
Can you tell me a bit about what you're trying to install, and the system you're trying to install it on?
